# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adsb_mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1550, 880)
        MainWindow.setMaximumSize(QtCore.QSize(1550, 880))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Administrator/.designer/backup/pic/airport.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTipDuration(0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(920, 370, 611, 491))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setGeometry(QtCore.QRect(10, 25, 591, 461))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_target = QtWidgets.QFrame(self.tab)
        self.frame_target.setGeometry(QtCore.QRect(0, 0, 591, 421))
        self.frame_target.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_target.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_target.setObjectName("frame_target")
        self.groupBox_tcas_target1 = QtWidgets.QGroupBox(self.frame_target)
        self.groupBox_tcas_target1.setGeometry(QtCore.QRect(310, 50, 271, 361))
        self.groupBox_tcas_target1.setObjectName("groupBox_tcas_target1")
        self.btn_stopsend_tcas_target1 = QtWidgets.QPushButton(self.groupBox_tcas_target1)
        self.btn_stopsend_tcas_target1.setGeometry(QtCore.QRect(10, 318, 251, 28))
        self.btn_stopsend_tcas_target1.setObjectName("btn_stopsend_tcas_target1")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_tcas_target1)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 251, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        self.label_27.setScaledContents(True)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.txt_Track_ID_target1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_Track_ID_target1.setEnabled(False)
        self.txt_Track_ID_target1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_Track_ID_target1.setText("")
        self.txt_Track_ID_target1.setObjectName("txt_Track_ID_target1")
        self.gridLayout_3.addWidget(self.txt_Track_ID_target1, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 1, 0, 1, 1)
        self.txt_Tcas_Altitude_target1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_Tcas_Altitude_target1.setEnabled(False)
        self.txt_Tcas_Altitude_target1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_Tcas_Altitude_target1.setText("")
        self.txt_Tcas_Altitude_target1.setObjectName("txt_Tcas_Altitude_target1")
        self.gridLayout_3.addWidget(self.txt_Tcas_Altitude_target1, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 2, 0, 1, 1)
        self.txt_Relative_Direction_target1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_Relative_Direction_target1.setEnabled(False)
        self.txt_Relative_Direction_target1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_Relative_Direction_target1.setText("")
        self.txt_Relative_Direction_target1.setObjectName("txt_Relative_Direction_target1")
        self.gridLayout_3.addWidget(self.txt_Relative_Direction_target1, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 3, 0, 1, 1)
        self.txt_Relative_Distance_target1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_Relative_Distance_target1.setEnabled(False)
        self.txt_Relative_Distance_target1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_Relative_Distance_target1.setText("")
        self.txt_Relative_Distance_target1.setObjectName("txt_Relative_Distance_target1")
        self.gridLayout_3.addWidget(self.txt_Relative_Distance_target1, 3, 1, 1, 1)
        self.btn_import_info_target1 = QtWidgets.QPushButton(self.frame_target)
        self.btn_import_info_target1.setGeometry(QtCore.QRect(10, 15, 241, 28))
        self.btn_import_info_target1.setObjectName("btn_import_info_target1")
        self.groupBox_adsb_target1 = QtWidgets.QGroupBox(self.frame_target)
        self.groupBox_adsb_target1.setGeometry(QtCore.QRect(10, 50, 291, 361))
        self.groupBox_adsb_target1.setObjectName("groupBox_adsb_target1")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_adsb_target1)
        self.layoutWidget1.setGeometry(QtCore.QRect(9, 34, 271, 318))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setMaximumSize(QtCore.QSize(144, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.txt_Heading_Track_Angle_target1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_Heading_Track_Angle_target1.setEnabled(False)
        self.txt_Heading_Track_Angle_target1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_Heading_Track_Angle_target1.setText("")
        self.txt_Heading_Track_Angle_target1.setObjectName("txt_Heading_Track_Angle_target1")
        self.gridLayout_2.addWidget(self.txt_Heading_Track_Angle_target1, 7, 1, 1, 1)
        self.txt_FlightID_target1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_FlightID_target1.setEnabled(False)
        self.txt_FlightID_target1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_FlightID_target1.setText("")
        self.txt_FlightID_target1.setObjectName("txt_FlightID_target1")
        self.gridLayout_2.addWidget(self.txt_FlightID_target1, 1, 1, 1, 1)
        self.txt_V_EW_target1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_V_EW_target1.setEnabled(False)
        self.txt_V_EW_target1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_V_EW_target1.setText("")
        self.txt_V_EW_target1.setObjectName("txt_V_EW_target1")
        self.gridLayout_2.addWidget(self.txt_V_EW_target1, 4, 1, 1, 1)
        self.txt_Latitude_target1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_Latitude_target1.setEnabled(False)
        self.txt_Latitude_target1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_Latitude_target1.setText("")
        self.txt_Latitude_target1.setObjectName("txt_Latitude_target1")
        self.gridLayout_2.addWidget(self.txt_Latitude_target1, 5, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_11.setScaledContents(True)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777214))
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 0, 1, 1)
        self.txt_V_SN_target1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_V_SN_target1.setEnabled(False)
        self.txt_V_SN_target1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_V_SN_target1.setText("")
        self.txt_V_SN_target1.setObjectName("txt_V_SN_target1")
        self.gridLayout_2.addWidget(self.txt_V_SN_target1, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 4, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_14.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.txt_Longitude_target1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_Longitude_target1.setEnabled(False)
        self.txt_Longitude_target1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_Longitude_target1.setText("")
        self.txt_Longitude_target1.setObjectName("txt_Longitude_target1")
        self.gridLayout_2.addWidget(self.txt_Longitude_target1, 6, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 8, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 7, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 5, 0, 1, 1)
        self.txt_ICAO_target1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_ICAO_target1.setEnabled(False)
        self.txt_ICAO_target1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_ICAO_target1.setText("")
        self.txt_ICAO_target1.setObjectName("txt_ICAO_target1")
        self.gridLayout_2.addWidget(self.txt_ICAO_target1, 0, 1, 1, 1)
        self.txt_Altitude_target1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_Altitude_target1.setEnabled(False)
        self.txt_Altitude_target1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_Altitude_target1.setText("")
        self.txt_Altitude_target1.setObjectName("txt_Altitude_target1")
        self.gridLayout_2.addWidget(self.txt_Altitude_target1, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 6, 0, 1, 1)
        self.txt_GroundSpeed_target1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.txt_GroundSpeed_target1.setEnabled(False)
        self.txt_GroundSpeed_target1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_GroundSpeed_target1.setText("")
        self.txt_GroundSpeed_target1.setObjectName("txt_GroundSpeed_target1")
        self.gridLayout_2.addWidget(self.txt_GroundSpeed_target1, 8, 1, 1, 1)
        self.btn_stopsend_adsb_target1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_stopsend_adsb_target1.setObjectName("btn_stopsend_adsb_target1")
        self.gridLayout_2.addWidget(self.btn_stopsend_adsb_target1, 9, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(1230, 0, 301, 361))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_start = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_start.setGeometry(QtCore.QRect(50, 120, 201, 28))
        self.btn_start.setObjectName("btn_start")
        self.btn_stop = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_stop.setEnabled(False)
        self.btn_stop.setGeometry(QtCore.QRect(50, 180, 201, 28))
        self.btn_stop.setObjectName("btn_stop")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(920, 0, 291, 361))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 30, 241, 318))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_GroundSpeed_own = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txt_GroundSpeed_own.setEnabled(False)
        self.txt_GroundSpeed_own.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_GroundSpeed_own.setText("")
        self.txt_GroundSpeed_own.setObjectName("txt_GroundSpeed_own")
        self.gridLayout.addWidget(self.txt_GroundSpeed_own, 13, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.txt_Altitude_own = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txt_Altitude_own.setEnabled(False)
        self.txt_Altitude_own.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_Altitude_own.setText("")
        self.txt_Altitude_own.setObjectName("txt_Altitude_own")
        self.gridLayout.addWidget(self.txt_Altitude_own, 3, 2, 1, 1)
        self.txt_FlightID_own = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txt_FlightID_own.setEnabled(False)
        self.txt_FlightID_own.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_FlightID_own.setText("")
        self.txt_FlightID_own.setObjectName("txt_FlightID_own")
        self.gridLayout.addWidget(self.txt_FlightID_own, 2, 2, 1, 1)
        self.txt_V_EW_own = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txt_V_EW_own.setEnabled(False)
        self.txt_V_EW_own.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_V_EW_own.setText("")
        self.txt_V_EW_own.setObjectName("txt_V_EW_own")
        self.gridLayout.addWidget(self.txt_V_EW_own, 5, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 1, 1, 1)
        self.txt_V_SN_own = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txt_V_SN_own.setEnabled(False)
        self.txt_V_SN_own.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_V_SN_own.setText("")
        self.txt_V_SN_own.setObjectName("txt_V_SN_own")
        self.gridLayout.addWidget(self.txt_V_SN_own, 4, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        self.txt_Heading_Track_Angle_own = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txt_Heading_Track_Angle_own.setEnabled(False)
        self.txt_Heading_Track_Angle_own.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_Heading_Track_Angle_own.setText("")
        self.txt_Heading_Track_Angle_own.setObjectName("txt_Heading_Track_Angle_own")
        self.gridLayout.addWidget(self.txt_Heading_Track_Angle_own, 9, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 1, 1, 1)
        self.txt_Longitude_own = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txt_Longitude_own.setEnabled(False)
        self.txt_Longitude_own.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_Longitude_own.setText("")
        self.txt_Longitude_own.setObjectName("txt_Longitude_own")
        self.gridLayout.addWidget(self.txt_Longitude_own, 8, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.txt_Latitude_own = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txt_Latitude_own.setEnabled(False)
        self.txt_Latitude_own.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_Latitude_own.setText("")
        self.txt_Latitude_own.setObjectName("txt_Latitude_own")
        self.gridLayout.addWidget(self.txt_Latitude_own, 6, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 13, 1, 1, 1)
        self.txt_ICAO_own = QtWidgets.QLineEdit(self.layoutWidget2)
        self.txt_ICAO_own.setEnabled(False)
        self.txt_ICAO_own.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txt_ICAO_own.setText("")
        self.txt_ICAO_own.setObjectName("txt_ICAO_own")
        self.gridLayout.addWidget(self.txt_ICAO_own, 1, 2, 1, 1)
        self.btn_import_info_own = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_import_info_own.setObjectName("btn_import_info_own")
        self.gridLayout.addWidget(self.btn_import_info_own, 0, 1, 1, 2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 901, 851))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutWidget6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "模拟飞机数据产生软件"))
        self.groupBox_2.setTitle(_translate("MainWindow", "目标机信息"))
        self.groupBox_tcas_target1.setTitle(_translate("MainWindow", "TCAS"))
        self.btn_stopsend_tcas_target1.setText(_translate("MainWindow", "暂停发送TCAS数据"))
        self.label_27.setText(_translate("MainWindow", "Track_ID："))
        self.label_26.setText(_translate("MainWindow", "压强高度(m)："))
        self.label_23.setText(_translate("MainWindow", "相对本机方位(deg)："))
        self.label_21.setText(_translate("MainWindow", "相对本机距离(km)："))
        self.btn_import_info_target1.setText(_translate("MainWindow", "导入飞机信息"))
        self.groupBox_adsb_target1.setTitle(_translate("MainWindow", "ADS-B"))
        self.label_4.setText(_translate("MainWindow", "压强高度(m)："))
        self.label_11.setText(_translate("MainWindow", "ICAO码："))
        self.label_12.setText(_translate("MainWindow", "南北速度(km/h)："))
        self.label_15.setText(_translate("MainWindow", "东西速度(km/h):"))
        self.label_14.setText(_translate("MainWindow", "航班号："))
        self.label_17.setText(_translate("MainWindow", "地速(km/h)："))
        self.label_18.setText(_translate("MainWindow", "航向角(deg)："))
        self.label_13.setText(_translate("MainWindow", "纬度(deg):"))
        self.label_16.setText(_translate("MainWindow", "经度(deg)："))
        self.btn_stopsend_adsb_target1.setText(_translate("MainWindow", "暂停发送ADS-B数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "1号目标机"))
        self.groupBox_3.setTitle(_translate("MainWindow", "控制台"))
        self.btn_start.setText(_translate("MainWindow", "开始"))
        self.btn_stop.setText(_translate("MainWindow", "停止"))
        self.groupBox.setTitle(_translate("MainWindow", "本机信息"))
        self.label_2.setText(_translate("MainWindow", "航班号："))
        self.label_7.setText(_translate("MainWindow", "纬度(deg):"))
        self.label_9.setText(_translate("MainWindow", "航向角(deg):"))
        self.label_3.setText(_translate("MainWindow", "压强高度(m)："))
        self.label_6.setText(_translate("MainWindow", "东西速度(km/h):"))
        self.label_8.setText(_translate("MainWindow", "经度(deg):"))
        self.label.setText(_translate("MainWindow", "ICAO码："))
        self.label_5.setText(_translate("MainWindow", "南北速度(km/h)："))
        self.label_10.setText(_translate("MainWindow", "地速(km/h):"))
        self.btn_import_info_own.setText(_translate("MainWindow", "导入飞机信息"))
        self.action1.setText(_translate("MainWindow", "本机"))
        self.action2.setText(_translate("MainWindow", "目标机"))

