#1号目标机 配置文件#
#模拟航路：银川-郑州
#tacs与ads-b关联且不为最佳源
ADS-B:
  fre_transmit_adsb: 1   #ads-b数据发送频率 单位s
  ICAO: 6324fo           #ICAO码
  Flight_ID: '3725CA'      #航班号
  Flight_24bit_addr: 0   #24位地址 默认为0
  Aircraft_Category: 0   #飞机类别 默认为0
  Altitude: 12500        #压强高度 单位m,默认为12500
  Radio_Altitude: 0      #几何高度 默认为0
  North_South_Velocity: 0     #南北速度 单位km/h 初始化0
  East_West_Velocity: 0       #东西速度 单位km/h 初始化0
  Vertical_Speed: 0     #垂直速度 默认为0
  Way_Point:            #所有航路点信息
    point1:
      - ZLIC         #航路点名称
      - 106.393333   #Longitude经度  单位deg
      - 38.320000      #Latitude纬度   单位deg
      - 0            #Heading_Track_Angle航向角  单位deg
    point2:
      - AKMAT
      - 107.750000
      - 38.200000
      - 96
    point3:
      - LUVES
      - 108.306667
      - 38.146667
      - 97
    point4:
      - APOGO
      - 110.665000
      - 37.930000
      - 96
    point5:
      - OMKAK
      - 111.716667
      - 37.835000
      - 96
    point6:
      - GODON
      - 112.351667
      - 37.775000
      - 97
    point7:
      - TYN
      - 112.620000
      - 37.748333
      - 97
    point8:
      - XIVEP
      - 112.658333
      - 37.631667
      - 165
    point9:
      - ANPIG
      - 112.850000
      - 37.055000
      - 165
    point10:
      - EGEBI
      - 112.936667
      - 36.793333
      - 165
    point11:
      - SQ
      - 113.116667
      - 36.240000
      - 165
    point12:
      - PADNO
      - 113.293333
      - 35.846667
      - 160
    point13:
      - TAMIX
      - 113.398333
      - 35.611667
      - 160
    point14:
      - ZHCC
      - 113.840000
      - 34.518333
      - 162
  Air_Ground_Sta: 0
  Ground_Speed: 900      #地速 单位km/h
  Flight_Length: 38.9    #飞机长度 单位m
  Flight_Width: 35.8     #飞机宽度 单位m
  NACV: 6    #速度不确定度 默认为6
  NACp: 0    #位置不确定度 默认为0
  NIC: 1     # 1 OR 0
  SIL: 1     # 1 OR 0
  SDA: 1
  emergency_priority_sta: 0
  data_link_version: 2
TCAS:
  enable: 1                    #是否有Tcas数据 有为1 无为0
  distance_to_own: 18.52       #目标机向本机发送Tcas数据的距离阈值 单位km 默认为10nm
  fre_transmit_tcas: 1         #Tcas数据发送频率 单位s
  Track_ID: 1
  Flight_24bit_addr_TCAS: 0    #24位地址
  Altitude_TCAS: 12500         #压强高度 单位m
  Vertical_Speed_TCAS: 0       #垂直速度
  Bearing: 0                   #相对本机方位 单位deg
  Range: 0                     #相对本机距离 单位km
  Warning_Status: 1            # 1 or 0
extra:
  delay_time: 0        #起飞延时 单位s