#1号目标机 配置文件#
#模拟航路：兰州-武汉
#tacs与ads-b关联且为最佳源

ADS-B:
  fre_transmit_adsb: 1   #ads-b数据发送频率 单位s
  ICAO: 9543c1           #ICAO码
  Flight_ID: '9C6187'      #航班号
  Flight_24bit_addr: 0   #24位地址 默认为0
  Aircraft_Category: 0   #飞机类别 默认为0
  Altitude: 12500        #压强高度 单位m,默认为12500
  Radio_Altitude: 0      #几何高度 默认为0
  North_South_Velocity: 0     #南北速度 单位km/h 初始化0
  East_West_Velocity: 0       #东西速度 单位km/h 初始化0
  Vertical_Speed: 0     #垂直速度 默认为0
  Way_Point:            #所有航路点信息
    point1:
      - ZLLL         #航路点名称
      - 103.620000   #Longitude经度  单位deg
      - 36.515       #Latitude纬度   单位deg
      - 0            #Heading_Track_Angle航向角  单位deg
    point2:
      - YHD
      - 106.41
      - 38.346667
      - 57
    point3:
      - MIMOK
      - 107.75
      - 38.2
      - 98
    point4:
      - LUVES
      - 108.306667
      - 38.146667
      - 97
    point5:
      - APOGO
      - 110.665
      - 37.93
      - 96
    point6:
      - OMKAK
      - 111.716667
      - 37.835
      - 96
    point7:
      - GODON
      - 112.351667
      - 37.775
      - 97
    point8:
      - TYN
      - 112.62
      - 37.748333
      - 97
    point9:
      - XIVEP
      - 112.658333
      - 37.631667
      - 165
    point10:
      - ANPIG
      - 112.85
      - 37.055
      - 165
    point11:
      - EGEBI
      - 112.936667
      - 36.793333
      - 165
    point12:
      - SQ
      - 113.116667
      - 36.24
      - 165
    point13:
      - PADNO
      - 113.293333
      - 35.846667
      - 160
    point14:
      - TAMIX
      - 113.398333
      - 35.611667
      - 160
    point15:
      - NOPIN
      - 113.471667
      - 35.446667
      - 160
    point16:
      - DUBAG
      - 113.730000
      - 34.863333
      - 160
    point17:
      - CGO
      - 113.843333
      - 34.518333
      - 165
    point18:
      - ZHO
      - 114.655
      - 33.665
      - 141
    point19:
      - FYG
      - 115.73
      - 32.883333
      - 131
    point20:
      - BIPIM
      - 116.183333
      - 32.565
      - 130
    point21:
      - PEDNU
      - 116.728333
      - 32.188333
      - 129
    point22:
      - MAGLI
      - 117.013333
      - 31.983333
      - 130
    point23:
      - HFE
      - 117.301667
      - 31.775
      - 130
    point24:
      - ZSNJ
      - 118.863333
      - 31.743333
      - 91
  Air_Ground_Sta: 0
  Ground_Speed: 960      #地速 单位km/h
  Flight_Length: 38.9    #飞机长度 单位m
  Flight_Width: 35.8     #飞机宽度 单位m
  NACV: 6    #速度不确定度 默认为6
  NACp: 3    #位置不确定度 默认为0
  NIC: 2     # 1 OR 0
  SIL: 1     # 1 OR 0
  SDA: 1
  emergency_priority_sta: 1
  data_link_version: 2
  # TCAS信息
  Track_ID: 1
  Flight_24bit_addr_TCAS: 0    #24位地址
  Altitude_TCAS: 12500         #压强高度 单位m
  Vertical_Speed_TCAS: 0       #垂直速度
  Bearing: 0                   #相对本机方位 单位deg
  Range: 0                     #相对本机距离 单位km
  Warning_Status: 1  # 1 or 0
TCAS:
  enable: 1                    #是否有Tcas数据 有为1 无为0
  distance_to_own: 18.52       #目标机向本机发送Tcas数据的距离阈值 单位km 默认为10nm
  fre_transmit_tcas: 1         #Tcas数据发送频率 单位s
  Track_ID: 1
  Flight_24bit_addr_TCAS: 0    #24位地址
  Altitude_TCAS: 12500         #压强高度 单位m
  Vertical_Speed_TCAS: 0       #垂直速度
  Bearing: 0                   #相对本机方位 单位deg
  Range: 0                     #相对本机距离 单位km
  Warning_Status: 1            # 1 or 0
extra:
  delay_time: 0        #起飞延时 单位s