# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cdti_mainform.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1380, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1380, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1380, 900))
        MainWindow.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1361, 871))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_AIRB = QtWidgets.QWidget()
        self.tab_AIRB.setObjectName("tab_AIRB")
        self.frame_2 = QtWidgets.QFrame(self.tab_AIRB)
        self.frame_2.setGeometry(QtCore.QRect(680, 20, 641, 831))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(40, 40, 151, 16))
        self.label_20.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_20.setObjectName("label_20")
        self.airb_ownship = QtWidgets.QLabel(self.frame_2)
        self.airb_ownship.setGeometry(QtCore.QRect(40, 70, 191, 16))
        self.airb_ownship.setStyleSheet("color:rgb(255, 255, 255)")
        self.airb_ownship.setObjectName("airb_ownship")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(40, 100, 161, 16))
        self.label_22.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_22.setObjectName("label_22")
        self.tableWidget_airb = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget_airb.setGeometry(QtCore.QRect(40, 150, 361, 192))
        self.tableWidget_airb.setObjectName("tableWidget_airb")
        self.tableWidget_airb.setColumnCount(2)
        self.tableWidget_airb.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget_airb.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget_airb.setHorizontalHeaderItem(1, item)
        self.frame_airb = QtWidgets.QFrame(self.tab_AIRB)
        self.frame_airb.setGeometry(QtCore.QRect(10, 20, 641, 821))
        self.frame_airb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_airb.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_airb.setObjectName("frame_airb")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_airb)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 591, 541))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.frame_airb)
        self.frame_9.setGeometry(QtCore.QRect(0, 710, 641, 101))
        self.frame_9.setStyleSheet("color:rgb(255, 255, 255)")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setLineWidth(1)
        self.frame_9.setObjectName("frame_9")
        self.label_37 = QtWidgets.QLabel(self.frame_9)
        self.label_37.setGeometry(QtCore.QRect(30, 20, 101, 16))
        self.label_37.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.frame_9)
        self.label_38.setGeometry(QtCore.QRect(30, 50, 121, 16))
        self.label_38.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.frame_9)
        self.label_39.setGeometry(QtCore.QRect(380, 60, 51, 16))
        self.label_39.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame_9)
        self.label_40.setGeometry(QtCore.QRect(380, 20, 131, 16))
        self.label_40.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame_9)
        self.label_41.setGeometry(QtCore.QRect(30, 80, 101, 16))
        self.label_41.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_41.setObjectName("label_41")
        self.btn_zoom_in_airb = QtWidgets.QPushButton(self.frame_9)
        self.btn_zoom_in_airb.setGeometry(QtCore.QRect(420, 50, 31, 31))
        self.btn_zoom_in_airb.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Administrator/.designer/backup/pic/+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_zoom_in_airb.setIcon(icon)
        self.btn_zoom_in_airb.setObjectName("btn_zoom_in_airb")
        self.btn_zoom_out_airb = QtWidgets.QPushButton(self.frame_9)
        self.btn_zoom_out_airb.setGeometry(QtCore.QRect(460, 50, 31, 31))
        self.btn_zoom_out_airb.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/Administrator/.designer/backup/pic/-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_zoom_out_airb.setIcon(icon1)
        self.btn_zoom_out_airb.setObjectName("btn_zoom_out_airb")
        self.airb_ownship_alt_txt = QtWidgets.QLabel(self.frame_9)
        self.airb_ownship_alt_txt.setGeometry(QtCore.QRect(140, 20, 61, 16))
        self.airb_ownship_alt_txt.setText("")
        self.airb_ownship_alt_txt.setObjectName("airb_ownship_alt_txt")
        self.airb_ownship_id_txt = QtWidgets.QLabel(self.frame_9)
        self.airb_ownship_id_txt.setGeometry(QtCore.QRect(480, 20, 61, 16))
        self.airb_ownship_id_txt.setText("")
        self.airb_ownship_id_txt.setObjectName("airb_ownship_id_txt")
        self.airb_time_txt = QtWidgets.QLabel(self.frame_9)
        self.airb_time_txt.setGeometry(QtCore.QRect(80, 50, 141, 16))
        self.airb_time_txt.setText("")
        self.airb_time_txt.setObjectName("airb_time_txt")
        self.airb_ownship_applstatus_bitmap = QtWidgets.QLabel(self.frame_9)
        self.airb_ownship_applstatus_bitmap.setGeometry(QtCore.QRect(140, 70, 31, 21))
        self.airb_ownship_applstatus_bitmap.setText("")
        self.airb_ownship_applstatus_bitmap.setObjectName("airb_ownship_applstatus_bitmap")
        self.label_65 = QtWidgets.QLabel(self.tab_AIRB)
        self.label_65.setGeometry(QtCore.QRect(10, 370, 16, 16))
        self.label_65.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_65.setObjectName("label_65")
        self.airb_compass_step2 = QtWidgets.QLabel(self.tab_AIRB)
        self.airb_compass_step2.setGeometry(QtCore.QRect(160, 710, 31, 16))
        self.airb_compass_step2.setStyleSheet("color:rgb(255, 255, 255)")
        self.airb_compass_step2.setObjectName("airb_compass_step2")
        self.airb_compass_step = QtWidgets.QLabel(self.tab_AIRB)
        self.airb_compass_step.setGeometry(QtCore.QRect(10, 220, 21, 16))
        self.airb_compass_step.setStyleSheet("color:rgb(255, 255, 255)")
        self.airb_compass_step.setObjectName("airb_compass_step")
        self.airb_compass_step6 = QtWidgets.QLabel(self.tab_AIRB)
        self.airb_compass_step6.setGeometry(QtCore.QRect(10, 710, 31, 16))
        self.airb_compass_step6.setStyleSheet("color:rgb(255, 255, 255)")
        self.airb_compass_step6.setObjectName("airb_compass_step6")
        self.airb_compass_step4 = QtWidgets.QLabel(self.tab_AIRB)
        self.airb_compass_step4.setGeometry(QtCore.QRect(640, 710, 21, 16))
        self.airb_compass_step4.setStyleSheet("color:rgb(255, 255, 255)")
        self.airb_compass_step4.setObjectName("airb_compass_step4")
        self.airb_compass_step3 = QtWidgets.QLabel(self.tab_AIRB)
        self.airb_compass_step3.setGeometry(QtCore.QRect(490, 710, 31, 16))
        self.airb_compass_step3.setStyleSheet("color:rgb(255, 255, 255)")
        self.airb_compass_step3.setObjectName("airb_compass_step3")
        self.label_62 = QtWidgets.QLabel(self.tab_AIRB)
        self.label_62.setGeometry(QtCore.QRect(330, 710, 21, 16))
        self.label_62.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_62.setObjectName("label_62")
        self.airb_compass_step1 = QtWidgets.QLabel(self.tab_AIRB)
        self.airb_compass_step1.setGeometry(QtCore.QRect(10, 70, 31, 16))
        self.airb_compass_step1.setStyleSheet("color:rgb(255, 255, 255)")
        self.airb_compass_step1.setObjectName("airb_compass_step1")
        self.airb_compass_step5 = QtWidgets.QLabel(self.tab_AIRB)
        self.airb_compass_step5.setGeometry(QtCore.QRect(10, 540, 31, 16))
        self.airb_compass_step5.setStyleSheet("color:rgb(255, 255, 255)")
        self.airb_compass_step5.setObjectName("airb_compass_step5")
        self.airb_ownship_lat_txt = QtWidgets.QLabel(self.tab_AIRB)
        self.airb_ownship_lat_txt.setGeometry(QtCore.QRect(1000, 60, 101, 16))
        self.airb_ownship_lat_txt.setStyleSheet("color:rgb(255, 255, 255)")
        self.airb_ownship_lat_txt.setObjectName("airb_ownship_lat_txt")
        self.airb_ownship_lon_txt = QtWidgets.QLabel(self.tab_AIRB)
        self.airb_ownship_lon_txt.setGeometry(QtCore.QRect(880, 60, 101, 16))
        self.airb_ownship_lon_txt.setStyleSheet("color:rgb(255, 255, 255)")
        self.airb_ownship_lon_txt.setObjectName("airb_ownship_lon_txt")
        self.airb_ownship_altrange_txt = QtWidgets.QLabel(self.tab_AIRB)
        self.airb_ownship_altrange_txt.setGeometry(QtCore.QRect(930, 90, 101, 16))
        self.airb_ownship_altrange_txt.setStyleSheet("color:rgb(255, 255, 255)")
        self.airb_ownship_altrange_txt.setObjectName("airb_ownship_altrange_txt")
        self.tabWidget.addTab(self.tab_AIRB, "")
        self.tab_SURF = QtWidgets.QWidget()
        self.tab_SURF.setObjectName("tab_SURF")
        self.frame_surf = QtWidgets.QFrame(self.tab_SURF)
        self.frame_surf.setGeometry(QtCore.QRect(10, 20, 641, 821))
        self.frame_surf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_surf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_surf.setObjectName("frame_surf")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_surf)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 591, 541))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_8 = QtWidgets.QFrame(self.frame_surf)
        self.frame_8.setGeometry(QtCore.QRect(0, 710, 641, 101))
        self.frame_8.setStyleSheet("color:rgb(255, 255, 255)")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setLineWidth(1)
        self.frame_8.setObjectName("frame_8")
        self.label_32 = QtWidgets.QLabel(self.frame_8)
        self.label_32.setGeometry(QtCore.QRect(30, 20, 101, 16))
        self.label_32.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.frame_8)
        self.label_33.setGeometry(QtCore.QRect(30, 50, 41, 16))
        self.label_33.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_8)
        self.label_34.setGeometry(QtCore.QRect(380, 60, 51, 16))
        self.label_34.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame_8)
        self.label_35.setGeometry(QtCore.QRect(380, 20, 101, 16))
        self.label_35.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_35.setObjectName("label_35")
        self.btn_zoom_in_surf = QtWidgets.QPushButton(self.frame_8)
        self.btn_zoom_in_surf.setGeometry(QtCore.QRect(430, 50, 31, 31))
        self.btn_zoom_in_surf.setText("")
        self.btn_zoom_in_surf.setIcon(icon)
        self.btn_zoom_in_surf.setObjectName("btn_zoom_in_surf")
        self.btn_zoom_out_surf = QtWidgets.QPushButton(self.frame_8)
        self.btn_zoom_out_surf.setGeometry(QtCore.QRect(470, 50, 31, 31))
        self.btn_zoom_out_surf.setText("")
        self.btn_zoom_out_surf.setIcon(icon1)
        self.btn_zoom_out_surf.setObjectName("btn_zoom_out_surf")
        self.label_36 = QtWidgets.QLabel(self.frame_8)
        self.label_36.setGeometry(QtCore.QRect(30, 80, 101, 16))
        self.label_36.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_36.setObjectName("label_36")
        self.surf_ownship_id_txt = QtWidgets.QLabel(self.frame_8)
        self.surf_ownship_id_txt.setGeometry(QtCore.QRect(490, 20, 61, 16))
        self.surf_ownship_id_txt.setStyleSheet("color:rgb(255, 255, 255)")
        self.surf_ownship_id_txt.setText("")
        self.surf_ownship_id_txt.setObjectName("surf_ownship_id_txt")
        self.surf_ownship_alt_txt = QtWidgets.QLabel(self.frame_8)
        self.surf_ownship_alt_txt.setGeometry(QtCore.QRect(150, 20, 61, 16))
        self.surf_ownship_alt_txt.setStyleSheet("color:rgb(255, 255, 255)")
        self.surf_ownship_alt_txt.setText("")
        self.surf_ownship_alt_txt.setObjectName("surf_ownship_alt_txt")
        self.surf_ownship_applstatus_bitmap = QtWidgets.QLabel(self.frame_8)
        self.surf_ownship_applstatus_bitmap.setGeometry(QtCore.QRect(140, 70, 31, 21))
        self.surf_ownship_applstatus_bitmap.setStyleSheet("color:rgb(255, 255, 255)")
        self.surf_ownship_applstatus_bitmap.setText("")
        self.surf_ownship_applstatus_bitmap.setObjectName("surf_ownship_applstatus_bitmap")
        self.surf_time_txt = QtWidgets.QLabel(self.frame_8)
        self.surf_time_txt.setGeometry(QtCore.QRect(90, 50, 131, 16))
        self.surf_time_txt.setText("")
        self.surf_time_txt.setObjectName("surf_time_txt")
        self.surf_compass_step6 = QtWidgets.QLabel(self.frame_surf)
        self.surf_compass_step6.setGeometry(QtCore.QRect(0, 690, 31, 16))
        self.surf_compass_step6.setStyleSheet("color:rgb(255, 255, 255)")
        self.surf_compass_step6.setObjectName("surf_compass_step6")
        self.frame_3 = QtWidgets.QFrame(self.tab_SURF)
        self.frame_3.setGeometry(QtCore.QRect(680, 20, 611, 831))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        self.label_24.setGeometry(QtCore.QRect(40, 40, 141, 16))
        self.label_24.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setGeometry(QtCore.QRect(40, 70, 191, 16))
        self.label_25.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(40, 100, 161, 16))
        self.label_26.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_26.setObjectName("label_26")
        self.surf_ownship_lon_txt = QtWidgets.QLabel(self.frame_3)
        self.surf_ownship_lon_txt.setGeometry(QtCore.QRect(200, 40, 101, 16))
        self.surf_ownship_lon_txt.setStyleSheet("color:rgb(255, 255, 255)")
        self.surf_ownship_lon_txt.setObjectName("surf_ownship_lon_txt")
        self.surf_ownship_lat_txt = QtWidgets.QLabel(self.frame_3)
        self.surf_ownship_lat_txt.setGeometry(QtCore.QRect(320, 40, 101, 16))
        self.surf_ownship_lat_txt.setStyleSheet("color:rgb(255, 255, 255)")
        self.surf_ownship_lat_txt.setObjectName("surf_ownship_lat_txt")
        self.surf_ownship_altrange_txt = QtWidgets.QLabel(self.frame_3)
        self.surf_ownship_altrange_txt.setGeometry(QtCore.QRect(250, 70, 101, 16))
        self.surf_ownship_altrange_txt.setStyleSheet("color:rgb(255, 255, 255)")
        self.surf_ownship_altrange_txt.setObjectName("surf_ownship_altrange_txt")
        self.tableWidget_surf = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget_surf.setGeometry(QtCore.QRect(40, 150, 361, 192))
        self.tableWidget_surf.setObjectName("tableWidget_surf")
        self.tableWidget_surf.setColumnCount(2)
        self.tableWidget_surf.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget_surf.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget_surf.setHorizontalHeaderItem(1, item)
        self.surf_compass_step1 = QtWidgets.QLabel(self.tab_SURF)
        self.surf_compass_step1.setGeometry(QtCore.QRect(10, 70, 31, 16))
        self.surf_compass_step1.setStyleSheet("color:rgb(255, 255, 255)")
        self.surf_compass_step1.setObjectName("surf_compass_step1")
        self.surf_compass_step2 = QtWidgets.QLabel(self.tab_SURF)
        self.surf_compass_step2.setGeometry(QtCore.QRect(160, 710, 31, 16))
        self.surf_compass_step2.setStyleSheet("color:rgb(255, 255, 255)")
        self.surf_compass_step2.setObjectName("surf_compass_step2")
        self.label_61 = QtWidgets.QLabel(self.tab_SURF)
        self.label_61.setGeometry(QtCore.QRect(330, 710, 21, 16))
        self.label_61.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_61.setObjectName("label_61")
        self.surf_compass_step3 = QtWidgets.QLabel(self.tab_SURF)
        self.surf_compass_step3.setGeometry(QtCore.QRect(490, 710, 31, 16))
        self.surf_compass_step3.setStyleSheet("color:rgb(255, 255, 255)")
        self.surf_compass_step3.setObjectName("surf_compass_step3")
        self.surf_compass_step4 = QtWidgets.QLabel(self.tab_SURF)
        self.surf_compass_step4.setGeometry(QtCore.QRect(640, 710, 21, 16))
        self.surf_compass_step4.setStyleSheet("color:rgb(255, 255, 255)")
        self.surf_compass_step4.setObjectName("surf_compass_step4")
        self.label_64 = QtWidgets.QLabel(self.tab_SURF)
        self.label_64.setGeometry(QtCore.QRect(10, 370, 16, 16))
        self.label_64.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_64.setObjectName("label_64")
        self.surf_compass_step = QtWidgets.QLabel(self.tab_SURF)
        self.surf_compass_step.setGeometry(QtCore.QRect(10, 220, 21, 16))
        self.surf_compass_step.setStyleSheet("color:rgb(255, 255, 255)")
        self.surf_compass_step.setObjectName("surf_compass_step")
        self.surf_compass_step5 = QtWidgets.QLabel(self.tab_SURF)
        self.surf_compass_step5.setGeometry(QtCore.QRect(10, 540, 31, 16))
        self.surf_compass_step5.setStyleSheet("color:rgb(255, 255, 255)")
        self.surf_compass_step5.setObjectName("surf_compass_step5")
        self.btn_close = QtWidgets.QPushButton(self.tab_SURF)
        self.btn_close.setGeometry(QtCore.QRect(200, 770, 93, 28))
        self.btn_close.setObjectName("btn_close")
        self.tabWidget.addTab(self.tab_SURF, "")
        self.tab_VSA = QtWidgets.QWidget()
        self.tab_VSA.setObjectName("tab_VSA")
        self.frame_vsa = QtWidgets.QFrame(self.tab_VSA)
        self.frame_vsa.setGeometry(QtCore.QRect(10, 20, 641, 821))
        self.frame_vsa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_vsa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_vsa.setObjectName("frame_vsa")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame_vsa)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 591, 541))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.frame_vsa)
        self.frame_10.setGeometry(QtCore.QRect(0, 710, 641, 101))
        self.frame_10.setStyleSheet("color:rgb(255, 255, 255)")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setLineWidth(1)
        self.frame_10.setObjectName("frame_10")
        self.label_42 = QtWidgets.QLabel(self.frame_10)
        self.label_42.setGeometry(QtCore.QRect(30, 20, 101, 16))
        self.label_42.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.frame_10)
        self.label_43.setGeometry(QtCore.QRect(30, 50, 51, 16))
        self.label_43.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.frame_10)
        self.label_44.setGeometry(QtCore.QRect(380, 60, 51, 16))
        self.label_44.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.frame_10)
        self.label_45.setGeometry(QtCore.QRect(380, 20, 101, 16))
        self.label_45.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame_10)
        self.label_46.setGeometry(QtCore.QRect(30, 80, 101, 16))
        self.label_46.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_46.setObjectName("label_46")
        self.btn_zoom_in_vsa = QtWidgets.QPushButton(self.frame_10)
        self.btn_zoom_in_vsa.setGeometry(QtCore.QRect(430, 50, 31, 31))
        self.btn_zoom_in_vsa.setText("")
        self.btn_zoom_in_vsa.setIcon(icon)
        self.btn_zoom_in_vsa.setObjectName("btn_zoom_in_vsa")
        self.btn_zoom_out_vsa = QtWidgets.QPushButton(self.frame_10)
        self.btn_zoom_out_vsa.setGeometry(QtCore.QRect(470, 50, 31, 31))
        self.btn_zoom_out_vsa.setText("")
        self.btn_zoom_out_vsa.setIcon(icon1)
        self.btn_zoom_out_vsa.setObjectName("btn_zoom_out_vsa")
        self.vsa_ownship_alt_txt = QtWidgets.QLabel(self.frame_10)
        self.vsa_ownship_alt_txt.setGeometry(QtCore.QRect(140, 20, 61, 16))
        self.vsa_ownship_alt_txt.setText("")
        self.vsa_ownship_alt_txt.setObjectName("vsa_ownship_alt_txt")
        self.vsa_ownship_id_txt = QtWidgets.QLabel(self.frame_10)
        self.vsa_ownship_id_txt.setGeometry(QtCore.QRect(500, 20, 61, 20))
        self.vsa_ownship_id_txt.setText("")
        self.vsa_ownship_id_txt.setObjectName("vsa_ownship_id_txt")
        self.vsa_time_txt = QtWidgets.QLabel(self.frame_10)
        self.vsa_time_txt.setGeometry(QtCore.QRect(80, 50, 121, 16))
        self.vsa_time_txt.setText("")
        self.vsa_time_txt.setObjectName("vsa_time_txt")
        self.vsa_ownship_applstatus_bitmap = QtWidgets.QLabel(self.frame_10)
        self.vsa_ownship_applstatus_bitmap.setGeometry(QtCore.QRect(140, 70, 31, 21))
        self.vsa_ownship_applstatus_bitmap.setStyleSheet("color:rgb(255, 255, 255)")
        self.vsa_ownship_applstatus_bitmap.setText("")
        self.vsa_ownship_applstatus_bitmap.setObjectName("vsa_ownship_applstatus_bitmap")
        self.frame_4 = QtWidgets.QFrame(self.tab_VSA)
        self.frame_4.setGeometry(QtCore.QRect(680, 20, 641, 831))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_28 = QtWidgets.QLabel(self.frame_4)
        self.label_28.setGeometry(QtCore.QRect(40, 40, 151, 16))
        self.label_28.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_4)
        self.label_29.setGeometry(QtCore.QRect(40, 70, 211, 16))
        self.label_29.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_4)
        self.label_30.setGeometry(QtCore.QRect(40, 100, 161, 16))
        self.label_30.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_30.setObjectName("label_30")
        self.vsa_ownship_lon_txt = QtWidgets.QLabel(self.frame_4)
        self.vsa_ownship_lon_txt.setGeometry(QtCore.QRect(200, 40, 101, 16))
        self.vsa_ownship_lon_txt.setStyleSheet("color:rgb(255, 255, 255)")
        self.vsa_ownship_lon_txt.setObjectName("vsa_ownship_lon_txt")
        self.vsa_ownship_lat_txt = QtWidgets.QLabel(self.frame_4)
        self.vsa_ownship_lat_txt.setGeometry(QtCore.QRect(320, 40, 101, 16))
        self.vsa_ownship_lat_txt.setStyleSheet("color:rgb(255, 255, 255)")
        self.vsa_ownship_lat_txt.setObjectName("vsa_ownship_lat_txt")
        self.tableWidget_vsa = QtWidgets.QTableWidget(self.frame_4)
        self.tableWidget_vsa.setGeometry(QtCore.QRect(40, 150, 551, 192))
        self.tableWidget_vsa.setObjectName("tableWidget_vsa")
        self.tableWidget_vsa.setColumnCount(4)
        self.tableWidget_vsa.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget_vsa.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget_vsa.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget_vsa.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget_vsa.setHorizontalHeaderItem(3, item)
        self.vsa_compass_step4 = QtWidgets.QLabel(self.tab_VSA)
        self.vsa_compass_step4.setGeometry(QtCore.QRect(640, 710, 21, 16))
        self.vsa_compass_step4.setStyleSheet("color:rgb(255, 255, 255)")
        self.vsa_compass_step4.setObjectName("vsa_compass_step4")
        self.vsa_compass_step1 = QtWidgets.QLabel(self.tab_VSA)
        self.vsa_compass_step1.setGeometry(QtCore.QRect(10, 70, 31, 16))
        self.vsa_compass_step1.setStyleSheet("color:rgb(255, 255, 255)")
        self.vsa_compass_step1.setObjectName("vsa_compass_step1")
        self.vsa_compass_step3 = QtWidgets.QLabel(self.tab_VSA)
        self.vsa_compass_step3.setGeometry(QtCore.QRect(490, 710, 31, 16))
        self.vsa_compass_step3.setStyleSheet("color:rgb(255, 255, 255)")
        self.vsa_compass_step3.setObjectName("vsa_compass_step3")
        self.vsa_compass_step = QtWidgets.QLabel(self.tab_VSA)
        self.vsa_compass_step.setGeometry(QtCore.QRect(10, 220, 21, 16))
        self.vsa_compass_step.setStyleSheet("color:rgb(255, 255, 255)")
        self.vsa_compass_step.setObjectName("vsa_compass_step")
        self.vsa_compass_step6 = QtWidgets.QLabel(self.tab_VSA)
        self.vsa_compass_step6.setGeometry(QtCore.QRect(10, 710, 31, 16))
        self.vsa_compass_step6.setStyleSheet("color:rgb(255, 255, 255)")
        self.vsa_compass_step6.setObjectName("vsa_compass_step6")
        self.label_63 = QtWidgets.QLabel(self.tab_VSA)
        self.label_63.setGeometry(QtCore.QRect(330, 710, 21, 16))
        self.label_63.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_63.setObjectName("label_63")
        self.label_66 = QtWidgets.QLabel(self.tab_VSA)
        self.label_66.setGeometry(QtCore.QRect(10, 370, 16, 16))
        self.label_66.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_66.setObjectName("label_66")
        self.vsa_compass_step2 = QtWidgets.QLabel(self.tab_VSA)
        self.vsa_compass_step2.setGeometry(QtCore.QRect(160, 710, 31, 16))
        self.vsa_compass_step2.setStyleSheet("color:rgb(255, 255, 255)")
        self.vsa_compass_step2.setObjectName("vsa_compass_step2")
        self.vsa_compass_step5 = QtWidgets.QLabel(self.tab_VSA)
        self.vsa_compass_step5.setGeometry(QtCore.QRect(10, 540, 31, 16))
        self.vsa_compass_step5.setStyleSheet("color:rgb(255, 255, 255)")
        self.vsa_compass_step5.setObjectName("vsa_compass_step5")
        self.vsa_ownship_altrange_txt = QtWidgets.QLabel(self.tab_VSA)
        self.vsa_ownship_altrange_txt.setGeometry(QtCore.QRect(930, 90, 101, 16))
        self.vsa_ownship_altrange_txt.setStyleSheet("color:rgb(255, 255, 255)")
        self.vsa_ownship_altrange_txt.setObjectName("vsa_ownship_altrange_txt")
        self.tabWidget.addTab(self.tab_VSA, "")
        self.tab_ITP = QtWidgets.QWidget()
        self.tab_ITP.setObjectName("tab_ITP")
        self.frame_itp = QtWidgets.QFrame(self.tab_ITP)
        self.frame_itp.setGeometry(QtCore.QRect(10, 20, 641, 821))
        self.frame_itp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_itp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_itp.setObjectName("frame_itp")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame_itp)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 591, 541))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_11 = QtWidgets.QFrame(self.frame_itp)
        self.frame_11.setGeometry(QtCore.QRect(0, 710, 641, 101))
        self.frame_11.setStyleSheet("color:rgb(255, 255, 255)")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setLineWidth(1)
        self.frame_11.setObjectName("frame_11")
        self.label_47 = QtWidgets.QLabel(self.frame_11)
        self.label_47.setGeometry(QtCore.QRect(30, 20, 101, 16))
        self.label_47.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.frame_11)
        self.label_48.setGeometry(QtCore.QRect(30, 50, 41, 16))
        self.label_48.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.frame_11)
        self.label_49.setGeometry(QtCore.QRect(380, 60, 51, 16))
        self.label_49.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.frame_11)
        self.label_50.setGeometry(QtCore.QRect(380, 20, 101, 16))
        self.label_50.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.frame_11)
        self.label_51.setGeometry(QtCore.QRect(30, 80, 101, 16))
        self.label_51.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_51.setObjectName("label_51")
        self.btn_zoom_in_itp = QtWidgets.QPushButton(self.frame_11)
        self.btn_zoom_in_itp.setGeometry(QtCore.QRect(430, 50, 31, 31))
        self.btn_zoom_in_itp.setText("")
        self.btn_zoom_in_itp.setIcon(icon)
        self.btn_zoom_in_itp.setObjectName("btn_zoom_in_itp")
        self.btn_zoom_out_itp = QtWidgets.QPushButton(self.frame_11)
        self.btn_zoom_out_itp.setGeometry(QtCore.QRect(470, 50, 31, 31))
        self.btn_zoom_out_itp.setText("")
        self.btn_zoom_out_itp.setIcon(icon1)
        self.btn_zoom_out_itp.setObjectName("btn_zoom_out_itp")
        self.itp_time_txt = QtWidgets.QLabel(self.frame_11)
        self.itp_time_txt.setGeometry(QtCore.QRect(90, 50, 131, 16))
        self.itp_time_txt.setText("")
        self.itp_time_txt.setObjectName("itp_time_txt")
        self.itp_ownship_applstatus_bitmap = QtWidgets.QLabel(self.frame_11)
        self.itp_ownship_applstatus_bitmap.setGeometry(QtCore.QRect(140, 70, 31, 21))
        self.itp_ownship_applstatus_bitmap.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_ownship_applstatus_bitmap.setText("")
        self.itp_ownship_applstatus_bitmap.setObjectName("itp_ownship_applstatus_bitmap")
        self.itp_ownship_alt_txt = QtWidgets.QLabel(self.frame_11)
        self.itp_ownship_alt_txt.setGeometry(QtCore.QRect(130, 20, 61, 16))
        self.itp_ownship_alt_txt.setText("")
        self.itp_ownship_alt_txt.setObjectName("itp_ownship_alt_txt")
        self.itp_ownship_id_txt = QtWidgets.QLabel(self.frame_11)
        self.itp_ownship_id_txt.setGeometry(QtCore.QRect(490, 20, 61, 16))
        self.itp_ownship_id_txt.setText("")
        self.itp_ownship_id_txt.setObjectName("itp_ownship_id_txt")
        self.frame_5 = QtWidgets.QFrame(self.tab_ITP)
        self.frame_5.setGeometry(QtCore.QRect(680, 20, 651, 831))
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_52 = QtWidgets.QLabel(self.frame_5)
        self.label_52.setGeometry(QtCore.QRect(40, 40, 151, 16))
        self.label_52.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.frame_5)
        self.label_53.setGeometry(QtCore.QRect(40, 70, 211, 16))
        self.label_53.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_53.setObjectName("label_53")
        self.img_itp_alt = QtWidgets.QLabel(self.frame_5)
        self.img_itp_alt.setGeometry(QtCore.QRect(0, 170, 621, 481))
        self.img_itp_alt.setText("")
        self.img_itp_alt.setPixmap(QtGui.QPixmap("C:/Users/Administrator/.designer/backup/pic/ITP.png"))
        self.img_itp_alt.setScaledContents(True)
        self.img_itp_alt.setObjectName("img_itp_alt")
        self.itp_own_dis1 = QtWidgets.QLabel(self.frame_5)
        self.itp_own_dis1.setGeometry(QtCore.QRect(90, 410, 21, 16))
        self.itp_own_dis1.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_own_dis1.setObjectName("itp_own_dis1")
        self.itp_own_dis2 = QtWidgets.QLabel(self.frame_5)
        self.itp_own_dis2.setGeometry(QtCore.QRect(210, 410, 21, 16))
        self.itp_own_dis2.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_own_dis2.setObjectName("itp_own_dis2")
        self.itp_own_dis3 = QtWidgets.QLabel(self.frame_5)
        self.itp_own_dis3.setGeometry(QtCore.QRect(435, 410, 21, 16))
        self.itp_own_dis3.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_own_dis3.setObjectName("itp_own_dis3")
        self.itp_own_dis4 = QtWidgets.QLabel(self.frame_5)
        self.itp_own_dis4.setGeometry(QtCore.QRect(550, 410, 21, 16))
        self.itp_own_dis4.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_own_dis4.setObjectName("itp_own_dis4")
        self.label_58 = QtWidgets.QLabel(self.frame_5)
        self.label_58.setGeometry(QtCore.QRect(325, 410, 21, 16))
        self.label_58.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_58.setObjectName("label_58")
        self.itp_own_alt = QtWidgets.QLabel(self.frame_5)
        self.itp_own_alt.setGeometry(QtCore.QRect(10, 390, 31, 16))
        self.itp_own_alt.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_own_alt.setObjectName("itp_own_alt")
        self.itp_own_alt4 = QtWidgets.QLabel(self.frame_5)
        self.itp_own_alt4.setGeometry(QtCore.QRect(10, 320, 31, 16))
        self.itp_own_alt4.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_own_alt4.setObjectName("itp_own_alt4")
        self.itp_own_alt5 = QtWidgets.QLabel(self.frame_5)
        self.itp_own_alt5.setGeometry(QtCore.QRect(10, 250, 31, 16))
        self.itp_own_alt5.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_own_alt5.setObjectName("itp_own_alt5")
        self.itp_own_alt6 = QtWidgets.QLabel(self.frame_5)
        self.itp_own_alt6.setGeometry(QtCore.QRect(10, 180, 31, 16))
        self.itp_own_alt6.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_own_alt6.setObjectName("itp_own_alt6")
        self.itp_own_alt3 = QtWidgets.QLabel(self.frame_5)
        self.itp_own_alt3.setGeometry(QtCore.QRect(10, 460, 31, 16))
        self.itp_own_alt3.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_own_alt3.setObjectName("itp_own_alt3")
        self.itp_own_alt2 = QtWidgets.QLabel(self.frame_5)
        self.itp_own_alt2.setGeometry(QtCore.QRect(10, 530, 31, 16))
        self.itp_own_alt2.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_own_alt2.setObjectName("itp_own_alt2")
        self.itp_own_alt1 = QtWidgets.QLabel(self.frame_5)
        self.itp_own_alt1.setGeometry(QtCore.QRect(10, 600, 31, 16))
        self.itp_own_alt1.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_own_alt1.setObjectName("itp_own_alt1")
        self.itp_compass_step4 = QtWidgets.QLabel(self.tab_ITP)
        self.itp_compass_step4.setGeometry(QtCore.QRect(640, 710, 21, 16))
        self.itp_compass_step4.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_compass_step4.setObjectName("itp_compass_step4")
        self.itp_compass_step1 = QtWidgets.QLabel(self.tab_ITP)
        self.itp_compass_step1.setGeometry(QtCore.QRect(10, 70, 31, 16))
        self.itp_compass_step1.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_compass_step1.setObjectName("itp_compass_step1")
        self.itp_compass_step3 = QtWidgets.QLabel(self.tab_ITP)
        self.itp_compass_step3.setGeometry(QtCore.QRect(490, 710, 31, 16))
        self.itp_compass_step3.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_compass_step3.setObjectName("itp_compass_step3")
        self.itp_compass_step = QtWidgets.QLabel(self.tab_ITP)
        self.itp_compass_step.setGeometry(QtCore.QRect(10, 220, 21, 16))
        self.itp_compass_step.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_compass_step.setObjectName("itp_compass_step")
        self.itp_compass_step6 = QtWidgets.QLabel(self.tab_ITP)
        self.itp_compass_step6.setGeometry(QtCore.QRect(10, 710, 31, 16))
        self.itp_compass_step6.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_compass_step6.setObjectName("itp_compass_step6")
        self.label_67 = QtWidgets.QLabel(self.tab_ITP)
        self.label_67.setGeometry(QtCore.QRect(330, 710, 21, 16))
        self.label_67.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_67.setObjectName("label_67")
        self.label_73 = QtWidgets.QLabel(self.tab_ITP)
        self.label_73.setGeometry(QtCore.QRect(10, 370, 16, 16))
        self.label_73.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_73.setObjectName("label_73")
        self.itp_compass_step2 = QtWidgets.QLabel(self.tab_ITP)
        self.itp_compass_step2.setGeometry(QtCore.QRect(160, 710, 31, 16))
        self.itp_compass_step2.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_compass_step2.setObjectName("itp_compass_step2")
        self.itp_compass_step5 = QtWidgets.QLabel(self.tab_ITP)
        self.itp_compass_step5.setGeometry(QtCore.QRect(10, 540, 31, 16))
        self.itp_compass_step5.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_compass_step5.setObjectName("itp_compass_step5")
        self.itp_ownship_altrange_txt = QtWidgets.QLabel(self.tab_ITP)
        self.itp_ownship_altrange_txt.setGeometry(QtCore.QRect(930, 90, 101, 16))
        self.itp_ownship_altrange_txt.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_ownship_altrange_txt.setObjectName("itp_ownship_altrange_txt")
        self.itp_ownship_lon_txt = QtWidgets.QLabel(self.tab_ITP)
        self.itp_ownship_lon_txt.setGeometry(QtCore.QRect(880, 60, 101, 16))
        self.itp_ownship_lon_txt.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_ownship_lon_txt.setObjectName("itp_ownship_lon_txt")
        self.itp_ownship_lat_txt = QtWidgets.QLabel(self.tab_ITP)
        self.itp_ownship_lat_txt.setGeometry(QtCore.QRect(1000, 60, 101, 16))
        self.itp_ownship_lat_txt.setStyleSheet("color:rgb(255, 255, 255)")
        self.itp_ownship_lat_txt.setObjectName("itp_ownship_lat_txt")
        self.tabWidget.addTab(self.tab_ITP, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1380, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_20.setText(_translate("MainWindow", "OWNSHIP POSITION:"))
        self.airb_ownship.setText(_translate("MainWindow", "DISPLAY ALTITUDE RANGE:"))
        self.label_22.setText(_translate("MainWindow", "TARGETS:"))
        item = self.tableWidget_airb.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_airb.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DIF_GROUNDSPEED KT"))
        self.label_37.setText(_translate("MainWindow", "OwnShip Alt："))
        self.label_38.setText(_translate("MainWindow", "Time："))
        self.label_39.setText(_translate("MainWindow", "ZOOM:"))
        self.label_40.setText(_translate("MainWindow", "OwnShip FID："))
        self.label_41.setText(_translate("MainWindow", "APPL Status："))
        self.label_65.setText(_translate("MainWindow", "0"))
        self.airb_compass_step2.setText(_translate("MainWindow", "-32"))
        self.airb_compass_step.setText(_translate("MainWindow", "32"))
        self.airb_compass_step6.setText(_translate("MainWindow", "-64"))
        self.airb_compass_step4.setText(_translate("MainWindow", "64"))
        self.airb_compass_step3.setText(_translate("MainWindow", "32"))
        self.label_62.setText(_translate("MainWindow", "0"))
        self.airb_compass_step1.setText(_translate("MainWindow", "-64"))
        self.airb_compass_step5.setText(_translate("MainWindow", "-32"))
        self.airb_ownship_lat_txt.setText(_translate("MainWindow", "ownship_lat"))
        self.airb_ownship_lon_txt.setText(_translate("MainWindow", "ownship_lon"))
        self.airb_ownship_altrange_txt.setText(_translate("MainWindow", "altrange"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_AIRB), _translate("MainWindow", "AIRB"))
        self.label_32.setText(_translate("MainWindow", "OwnShip Alt："))
        self.label_33.setText(_translate("MainWindow", "Time："))
        self.label_34.setText(_translate("MainWindow", "ZOOM:"))
        self.label_35.setText(_translate("MainWindow", "OwnShip FID："))
        self.label_36.setText(_translate("MainWindow", "APPL Status："))
        self.surf_compass_step6.setText(_translate("MainWindow", "-64"))
        self.label_24.setText(_translate("MainWindow", "OWNSHIP POSITION:"))
        self.label_25.setText(_translate("MainWindow", "DISPLAY ALTITUDE RANGE:"))
        self.label_26.setText(_translate("MainWindow", "TARGETS:"))
        self.surf_ownship_lon_txt.setText(_translate("MainWindow", "ownship_lon"))
        self.surf_ownship_lat_txt.setText(_translate("MainWindow", "ownship_lat"))
        self.surf_ownship_altrange_txt.setText(_translate("MainWindow", "altrange"))
        item = self.tableWidget_surf.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_surf.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DIF_GROUNDSPEED KT"))
        self.surf_compass_step1.setText(_translate("MainWindow", "-64"))
        self.surf_compass_step2.setText(_translate("MainWindow", "-32"))
        self.label_61.setText(_translate("MainWindow", "0"))
        self.surf_compass_step3.setText(_translate("MainWindow", "32"))
        self.surf_compass_step4.setText(_translate("MainWindow", "64"))
        self.label_64.setText(_translate("MainWindow", "0"))
        self.surf_compass_step.setText(_translate("MainWindow", "32"))
        self.surf_compass_step5.setText(_translate("MainWindow", "-32"))
        self.btn_close.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_SURF), _translate("MainWindow", "SURF"))
        self.label_42.setText(_translate("MainWindow", "OwnShip Alt："))
        self.label_43.setText(_translate("MainWindow", "Time："))
        self.label_44.setText(_translate("MainWindow", "ZOOM:"))
        self.label_45.setText(_translate("MainWindow", "OwnShip FID："))
        self.label_46.setText(_translate("MainWindow", "APPL Status："))
        self.label_28.setText(_translate("MainWindow", "OWNSHIP POSITION:"))
        self.label_29.setText(_translate("MainWindow", "DISPLAY ALTITUDE RANGE:"))
        self.label_30.setText(_translate("MainWindow", "TARGETS:"))
        self.vsa_ownship_lon_txt.setText(_translate("MainWindow", "ownship_lon"))
        self.vsa_ownship_lat_txt.setText(_translate("MainWindow", "ownship_lat"))
        item = self.tableWidget_vsa.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_vsa.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DIF_GDSPEED KT"))
        item = self.tableWidget_vsa.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "HORIZONTAL_DIS NM"))
        item = self.tableWidget_vsa.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "VELOCITY"))
        self.vsa_compass_step4.setText(_translate("MainWindow", "64"))
        self.vsa_compass_step1.setText(_translate("MainWindow", "-64"))
        self.vsa_compass_step3.setText(_translate("MainWindow", "32"))
        self.vsa_compass_step.setText(_translate("MainWindow", "32"))
        self.vsa_compass_step6.setText(_translate("MainWindow", "-64"))
        self.label_63.setText(_translate("MainWindow", "0"))
        self.label_66.setText(_translate("MainWindow", "0"))
        self.vsa_compass_step2.setText(_translate("MainWindow", "-32"))
        self.vsa_compass_step5.setText(_translate("MainWindow", "-32"))
        self.vsa_ownship_altrange_txt.setText(_translate("MainWindow", "altrange"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_VSA), _translate("MainWindow", "VSA"))
        self.label_47.setText(_translate("MainWindow", "OwnShip Alt："))
        self.label_48.setText(_translate("MainWindow", "Time："))
        self.label_49.setText(_translate("MainWindow", "ZOOM:"))
        self.label_50.setText(_translate("MainWindow", "OwnShip FID："))
        self.label_51.setText(_translate("MainWindow", "APPL Status："))
        self.label_52.setText(_translate("MainWindow", "OWNSHIP POSITION:"))
        self.label_53.setText(_translate("MainWindow", "DISPLAY ALTITUDE RANGE:"))
        self.itp_own_dis1.setText(_translate("MainWindow", "64"))
        self.itp_own_dis2.setText(_translate("MainWindow", "32"))
        self.itp_own_dis3.setText(_translate("MainWindow", "32"))
        self.itp_own_dis4.setText(_translate("MainWindow", "64"))
        self.label_58.setText(_translate("MainWindow", "0"))
        self.itp_own_alt.setText(_translate("MainWindow", "320"))
        self.itp_own_alt4.setText(_translate("MainWindow", "330"))
        self.itp_own_alt5.setText(_translate("MainWindow", "340"))
        self.itp_own_alt6.setText(_translate("MainWindow", "350"))
        self.itp_own_alt3.setText(_translate("MainWindow", "310"))
        self.itp_own_alt2.setText(_translate("MainWindow", "300"))
        self.itp_own_alt1.setText(_translate("MainWindow", "290"))
        self.itp_compass_step4.setText(_translate("MainWindow", "64"))
        self.itp_compass_step1.setText(_translate("MainWindow", "-64"))
        self.itp_compass_step3.setText(_translate("MainWindow", "32"))
        self.itp_compass_step.setText(_translate("MainWindow", "32"))
        self.itp_compass_step6.setText(_translate("MainWindow", "-64"))
        self.label_67.setText(_translate("MainWindow", "0"))
        self.label_73.setText(_translate("MainWindow", "0"))
        self.itp_compass_step2.setText(_translate("MainWindow", "-32"))
        self.itp_compass_step5.setText(_translate("MainWindow", "-32"))
        self.itp_ownship_altrange_txt.setText(_translate("MainWindow", "altrange"))
        self.itp_ownship_lon_txt.setText(_translate("MainWindow", "ownship_lon"))
        self.itp_ownship_lat_txt.setText(_translate("MainWindow", "ownship_lat"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ITP), _translate("MainWindow", "ITP"))

