# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cdti_mainform.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1380, 950)
        MainWindow.setMinimumSize(QtCore.QSize(1380, 950))
        MainWindow.setMaximumSize(QtCore.QSize(1380, 950))
        MainWindow.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 1351, 901))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_AIRB = QtWidgets.QWidget()
        self.tab_AIRB.setObjectName("tab_AIRB")
        self.frame = QtWidgets.QFrame(self.tab_AIRB)
        self.frame.setGeometry(QtCore.QRect(10, 20, 659, 841))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 645, 800))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("pic/b.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(2, 45, 640, 640))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("pic/c.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(0, 700, 645, 131))
        self.frame_4.setStyleSheet("color:rgb(255, 255, 255)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(1)
        self.frame_4.setObjectName("frame_4")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 121, 16))
        self.label_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(30, 60, 121, 16))
        self.label_6.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(240, 70, 51, 16))
        self.label_8.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(240, 30, 131, 16))
        self.label_4.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.btn_zoom_add = QtWidgets.QPushButton(self.frame_4)
        self.btn_zoom_add.setGeometry(QtCore.QRect(280, 60, 31, 31))
        self.btn_zoom_add.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pic/+.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_zoom_add.setIcon(icon)
        self.btn_zoom_add.setObjectName("btn_zoom_add")
        self.btn_zoom_reduce = QtWidgets.QPushButton(self.frame_4)
        self.btn_zoom_reduce.setGeometry(QtCore.QRect(310, 60, 31, 31))
        self.btn_zoom_reduce.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pic/-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_zoom_reduce.setIcon(icon1)
        self.btn_zoom_reduce.setObjectName("btn_zoom_reduce")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(30, 90, 121, 16))
        self.label_7.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_7.setObjectName("label_7")
        self.label.raise_()
        self.frame_4.raise_()
        self.label_24.raise_()
        self.frame_2 = QtWidgets.QFrame(self.tab_AIRB)
        self.frame_2.setGeometry(QtCore.QRect(680, 20, 641, 831))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(40, 40, 121, 16))
        self.label_20.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(40, 70, 161, 16))
        self.label_21.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(40, 100, 161, 16))
        self.label_22.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setGeometry(QtCore.QRect(70, 130, 211, 16))
        self.label_23.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_23.setObjectName("label_23")
        self.tabWidget.addTab(self.tab_AIRB, "")
        self.tab_SURF = QtWidgets.QWidget()
        self.tab_SURF.setObjectName("tab_SURF")
        self.frame_3 = QtWidgets.QFrame(self.tab_SURF)
        self.frame_3.setGeometry(QtCore.QRect(10, 20, 641, 821))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 591, 541))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setGeometry(QtCore.QRect(0, 710, 641, 111))
        self.frame_8.setStyleSheet("color:rgb(255, 255, 255)")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setLineWidth(1)
        self.frame_8.setObjectName("frame_8")
        self.label_32 = QtWidgets.QLabel(self.frame_8)
        self.label_32.setGeometry(QtCore.QRect(30, 30, 121, 16))
        self.label_32.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.frame_8)
        self.label_33.setGeometry(QtCore.QRect(30, 60, 121, 16))
        self.label_33.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_8)
        self.label_34.setGeometry(QtCore.QRect(240, 70, 51, 16))
        self.label_34.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame_8)
        self.label_35.setGeometry(QtCore.QRect(240, 30, 131, 16))
        self.label_35.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_35.setObjectName("label_35")
        self.btn_zoom_add_4 = QtWidgets.QPushButton(self.frame_8)
        self.btn_zoom_add_4.setGeometry(QtCore.QRect(280, 60, 31, 31))
        self.btn_zoom_add_4.setText("")
        self.btn_zoom_add_4.setIcon(icon)
        self.btn_zoom_add_4.setObjectName("btn_zoom_add_4")
        self.btn_zoom_reduce_4 = QtWidgets.QPushButton(self.frame_8)
        self.btn_zoom_reduce_4.setGeometry(QtCore.QRect(310, 60, 31, 31))
        self.btn_zoom_reduce_4.setText("")
        self.btn_zoom_reduce_4.setIcon(icon1)
        self.btn_zoom_reduce_4.setObjectName("btn_zoom_reduce_4")
        self.label_36 = QtWidgets.QLabel(self.frame_8)
        self.label_36.setGeometry(QtCore.QRect(30, 90, 121, 16))
        self.label_36.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_36.setObjectName("label_36")
        self.tabWidget.addTab(self.tab_SURF, "")
        self.tab_VSA = QtWidgets.QWidget()
        self.tab_VSA.setObjectName("tab_VSA")
        self.frame_5 = QtWidgets.QFrame(self.tab_VSA)
        self.frame_5.setGeometry(QtCore.QRect(10, 20, 411, 641))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(-10, 0, 421, 571))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("pic/b.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_37 = QtWidgets.QLabel(self.frame_5)
        self.label_37.setGeometry(QtCore.QRect(20, 60, 380, 380))
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("pic/d.png"))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setGeometry(QtCore.QRect(3, 490, 408, 131))
        self.frame_9.setStyleSheet("color:rgb(255, 255, 255)")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setLineWidth(1)
        self.frame_9.setObjectName("frame_9")
        self.label_38 = QtWidgets.QLabel(self.frame_9)
        self.label_38.setGeometry(QtCore.QRect(30, 30, 121, 16))
        self.label_38.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.frame_9)
        self.label_39.setGeometry(QtCore.QRect(30, 60, 121, 16))
        self.label_39.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame_9)
        self.label_40.setGeometry(QtCore.QRect(240, 70, 51, 16))
        self.label_40.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame_9)
        self.label_41.setGeometry(QtCore.QRect(240, 30, 131, 16))
        self.label_41.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_41.setObjectName("label_41")
        self.btn_zoom_add_5 = QtWidgets.QPushButton(self.frame_9)
        self.btn_zoom_add_5.setGeometry(QtCore.QRect(280, 60, 31, 31))
        self.btn_zoom_add_5.setText("")
        self.btn_zoom_add_5.setIcon(icon)
        self.btn_zoom_add_5.setObjectName("btn_zoom_add_5")
        self.btn_zoom_reduce_5 = QtWidgets.QPushButton(self.frame_9)
        self.btn_zoom_reduce_5.setGeometry(QtCore.QRect(310, 60, 31, 31))
        self.btn_zoom_reduce_5.setText("")
        self.btn_zoom_reduce_5.setIcon(icon1)
        self.btn_zoom_reduce_5.setObjectName("btn_zoom_reduce_5")
        self.label_42 = QtWidgets.QLabel(self.frame_9)
        self.label_42.setGeometry(QtCore.QRect(30, 90, 121, 16))
        self.label_42.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_42.setObjectName("label_42")
        self.tabWidget.addTab(self.tab_VSA, "")
        self.tab_ITP = QtWidgets.QWidget()
        self.tab_ITP.setObjectName("tab_ITP")
        self.frame_10 = QtWidgets.QFrame(self.tab_ITP)
        self.frame_10.setGeometry(QtCore.QRect(10, 20, 411, 641))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_43 = QtWidgets.QLabel(self.frame_10)
        self.label_43.setGeometry(QtCore.QRect(-10, 0, 421, 571))
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap("pic/b.png"))
        self.label_43.setScaledContents(True)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.frame_10)
        self.label_44.setGeometry(QtCore.QRect(20, 60, 380, 380))
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap("pic/d.png"))
        self.label_44.setScaledContents(True)
        self.label_44.setObjectName("label_44")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setGeometry(QtCore.QRect(3, 490, 408, 131))
        self.frame_11.setStyleSheet("color:rgb(255, 255, 255)")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setLineWidth(1)
        self.frame_11.setObjectName("frame_11")
        self.label_45 = QtWidgets.QLabel(self.frame_11)
        self.label_45.setGeometry(QtCore.QRect(30, 30, 121, 16))
        self.label_45.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame_11)
        self.label_46.setGeometry(QtCore.QRect(30, 60, 121, 16))
        self.label_46.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.frame_11)
        self.label_47.setGeometry(QtCore.QRect(240, 70, 51, 16))
        self.label_47.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.frame_11)
        self.label_48.setGeometry(QtCore.QRect(240, 30, 131, 16))
        self.label_48.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_48.setObjectName("label_48")
        self.btn_zoom_add_6 = QtWidgets.QPushButton(self.frame_11)
        self.btn_zoom_add_6.setGeometry(QtCore.QRect(280, 60, 31, 31))
        self.btn_zoom_add_6.setText("")
        self.btn_zoom_add_6.setIcon(icon)
        self.btn_zoom_add_6.setObjectName("btn_zoom_add_6")
        self.btn_zoom_reduce_6 = QtWidgets.QPushButton(self.frame_11)
        self.btn_zoom_reduce_6.setGeometry(QtCore.QRect(310, 60, 31, 31))
        self.btn_zoom_reduce_6.setText("")
        self.btn_zoom_reduce_6.setIcon(icon1)
        self.btn_zoom_reduce_6.setObjectName("btn_zoom_reduce_6")
        self.label_49 = QtWidgets.QLabel(self.frame_11)
        self.label_49.setGeometry(QtCore.QRect(30, 90, 121, 16))
        self.label_49.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_49.setObjectName("label_49")
        self.tabWidget.addTab(self.tab_ITP, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1380, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "OwnShip Alt："))
        self.label_6.setText(_translate("MainWindow", "Time："))
        self.label_8.setText(_translate("MainWindow", "ZOOM:"))
        self.label_4.setText(_translate("MainWindow", "OwnShip FID："))
        self.label_7.setText(_translate("MainWindow", "APPL Status："))
        self.label_20.setText(_translate("MainWindow", "OWNSHIP POSITION:"))
        self.label_21.setText(_translate("MainWindow", "DISPLAY ALTITUDE RANGE:"))
        self.label_22.setText(_translate("MainWindow", "TARGETS:"))
        self.label_23.setText(_translate("MainWindow", "ID               GROUNDSPEED KT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_AIRB), _translate("MainWindow", "AIRB"))
        self.label_32.setText(_translate("MainWindow", "OwnShip Alt："))
        self.label_33.setText(_translate("MainWindow", "Time："))
        self.label_34.setText(_translate("MainWindow", "ZOOM:"))
        self.label_35.setText(_translate("MainWindow", "OwnShip FID："))
        self.label_36.setText(_translate("MainWindow", "APPL Status："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_SURF), _translate("MainWindow", "SURF"))
        self.label_38.setText(_translate("MainWindow", "OwnShip Alt："))
        self.label_39.setText(_translate("MainWindow", "Time："))
        self.label_40.setText(_translate("MainWindow", "ZOOM:"))
        self.label_41.setText(_translate("MainWindow", "OwnShip FID："))
        self.label_42.setText(_translate("MainWindow", "APPL Status："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_VSA), _translate("MainWindow", "VSA"))
        self.label_45.setText(_translate("MainWindow", "OwnShip Alt："))
        self.label_46.setText(_translate("MainWindow", "Time："))
        self.label_47.setText(_translate("MainWindow", "ZOOM:"))
        self.label_48.setText(_translate("MainWindow", "OwnShip FID："))
        self.label_49.setText(_translate("MainWindow", "APPL Status："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ITP), _translate("MainWindow", "ITP"))

