# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'daa_ui1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.tabWidget.setMinimumSize(QtCore.QSize(1024, 768))
        self.tabWidget.setMaximumSize(QtCore.QSize(1024, 768))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(5, 5, 1012, 65))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(30, 20, 961, 20))
        self.label_9.setStyleSheet("color:lightblue;font-size:16px")
        self.label_9.setObjectName("label_9")
        self.btn_jump1 = QtWidgets.QPushButton(self.frame)
        self.btn_jump1.setGeometry(QtCore.QRect(920, 2, 91, 61))
        self.btn_jump1.setStyleSheet("color:white")
        self.btn_jump1.setObjectName("btn_jump1")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(591, 442, 426, 331))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(405, 145, 72, 21))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("pic/youbiao.png"))
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 16, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("pic/gaodu1.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(10, 230, 16, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("pic/gaodu2.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_1 = QtWidgets.QLabel(self.frame_3)
        self.label_1.setGeometry(QtCore.QRect(10, 30, 16, 31))
        self.label_1.setText("")
        self.label_1.setPixmap(QtGui.QPixmap("pic/gaodu2.png"))
        self.label_1.setScaledContents(True)
        self.label_1.setObjectName("label_1")
        self.txt_xiakedu2_2 = QtWidgets.QLabel(self.frame_3)
        self.txt_xiakedu2_2.setGeometry(QtCore.QRect(55, 270, 280, 20))
        self.txt_xiakedu2_2.setStyleSheet("color:white")
        self.txt_xiakedu2_2.setText("")
        self.txt_xiakedu2_2.setPixmap(QtGui.QPixmap("pic/下刻度.png"))
        self.txt_xiakedu2_2.setScaledContents(True)
        self.txt_xiakedu2_2.setObjectName("txt_xiakedu2_2")
        self.alt_label1 = QtWidgets.QLabel(self.frame_3)
        self.alt_label1.setGeometry(QtCore.QRect(30, 37, 32, 16))
        self.alt_label1.setStyleSheet("color:blue")
        self.alt_label1.setObjectName("alt_label1")
        self.alt_label2 = QtWidgets.QLabel(self.frame_3)
        self.alt_label2.setGeometry(QtCore.QRect(30, 137, 32, 16))
        self.alt_label2.setStyleSheet("color:white")
        self.alt_label2.setObjectName("alt_label2")
        self.alt_label3 = QtWidgets.QLabel(self.frame_3)
        self.alt_label3.setGeometry(QtCore.QRect(30, 237, 32, 16))
        self.alt_label3.setStyleSheet("color:blue")
        self.alt_label3.setObjectName("alt_label3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(400, 55, 18, 200))
        self.label.setStyleSheet("background-color:transparent")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("pic/kedu3.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_lanse = QtWidgets.QLabel(self.frame_3)
        self.label_lanse.setGeometry(QtCore.QRect(363, 130, 36, 46))
        self.label_lanse.setStyleSheet("background-color:transparent")
        self.label_lanse.setText("")
        self.label_lanse.setPixmap(QtGui.QPixmap("pic/lanse2.png"))
        self.label_lanse.setObjectName("label_lanse")
        self.angle_kedu_txt = QtWidgets.QLabel(self.frame_3)
        self.angle_kedu_txt.setGeometry(QtCore.QRect(368, 145, 31, 16))
        self.angle_kedu_txt.setStyleSheet("color:white;background-color:transparent")
        self.angle_kedu_txt.setObjectName("angle_kedu_txt")
        self.listWidget_1 = QtWidgets.QListWidget(self.frame_3)
        self.listWidget_1.setGeometry(QtCore.QRect(355, 10, 45, 285))
        self.listWidget_1.setObjectName("listWidget_1")
        self.tab1_own_pix = QtWidgets.QLabel(self.frame_3)
        self.tab1_own_pix.setEnabled(True)
        self.tab1_own_pix.setGeometry(QtCore.QRect(180, 140, 25, 10))
        self.tab1_own_pix.setText("")
        self.tab1_own_pix.setPixmap(QtGui.QPixmap("pic/benji.png"))
        self.tab1_own_pix.setObjectName("tab1_own_pix")
        self.tab1_target1_info = QtWidgets.QLabel(self.frame_3)
        self.tab1_target1_info.setGeometry(QtCore.QRect(40, 80, 66, 22))
        self.tab1_target1_info.setObjectName("tab1_target1_info")
        self.tab1_target2_info = QtWidgets.QLabel(self.frame_3)
        self.tab1_target2_info.setGeometry(QtCore.QRect(110, 80, 51, 16))
        self.tab1_target2_info.setObjectName("tab1_target2_info")
        self.tab1_target3_info = QtWidgets.QLabel(self.frame_3)
        self.tab1_target3_info.setGeometry(QtCore.QRect(280, 90, 51, 16))
        self.tab1_target3_info.setObjectName("tab1_target3_info")
        self.tab1_target4_info = QtWidgets.QLabel(self.frame_3)
        self.tab1_target4_info.setGeometry(QtCore.QRect(160, 90, 51, 16))
        self.tab1_target4_info.setObjectName("tab1_target4_info")
        self.tab1_target5_info = QtWidgets.QLabel(self.frame_3)
        self.tab1_target5_info.setGeometry(QtCore.QRect(220, 90, 51, 16))
        self.tab1_target5_info.setObjectName("tab1_target5_info")
        self.tab1_target1_pix = QtWidgets.QLabel(self.frame_3)
        self.tab1_target1_pix.setGeometry(QtCore.QRect(50, 70, 25, 10))
        self.tab1_target1_pix.setText("")
        self.tab1_target1_pix.setPixmap(QtGui.QPixmap("pic/qtfeiji1.png"))
        self.tab1_target1_pix.setObjectName("tab1_target1_pix")
        self.tab1_target2_pix = QtWidgets.QLabel(self.frame_3)
        self.tab1_target2_pix.setGeometry(QtCore.QRect(110, 70, 25, 10))
        self.tab1_target2_pix.setText("")
        self.tab1_target2_pix.setPixmap(QtGui.QPixmap("pic/qtfeiji2.png"))
        self.tab1_target2_pix.setObjectName("tab1_target2_pix")
        self.tab1_target3_pix = QtWidgets.QLabel(self.frame_3)
        self.tab1_target3_pix.setGeometry(QtCore.QRect(290, 70, 25, 10))
        self.tab1_target3_pix.setText("")
        self.tab1_target3_pix.setPixmap(QtGui.QPixmap("pic/qtfeiji3.png"))
        self.tab1_target3_pix.setObjectName("tab1_target3_pix")
        self.tab1_target4_pix = QtWidgets.QLabel(self.frame_3)
        self.tab1_target4_pix.setGeometry(QtCore.QRect(170, 80, 25, 10))
        self.tab1_target4_pix.setText("")
        self.tab1_target4_pix.setPixmap(QtGui.QPixmap("pic/benji.png"))
        self.tab1_target4_pix.setObjectName("tab1_target4_pix")
        self.tab1_target5_pix = QtWidgets.QLabel(self.frame_3)
        self.tab1_target5_pix.setGeometry(QtCore.QRect(230, 80, 25, 10))
        self.tab1_target5_pix.setText("")
        self.tab1_target5_pix.setPixmap(QtGui.QPixmap("pic/benji.png"))
        self.tab1_target5_pix.setObjectName("tab1_target5_pix")
        self.tab1_line1 = QtWidgets.QLabel(self.frame_3)
        self.tab1_line1.setGeometry(QtCore.QRect(70, 45, 248, 1))
        self.tab1_line1.setText("")
        self.tab1_line1.setPixmap(QtGui.QPixmap("pic/Line 3-2.png"))
        self.tab1_line1.setObjectName("tab1_line1")
        self.tab1_line2 = QtWidgets.QLabel(self.frame_3)
        self.tab1_line2.setGeometry(QtCore.QRect(70, 145, 248, 1))
        self.tab1_line2.setText("")
        self.tab1_line2.setPixmap(QtGui.QPixmap("pic/Line 3-1.png"))
        self.tab1_line2.setObjectName("tab1_line2")
        self.tab1_line3 = QtWidgets.QLabel(self.frame_3)
        self.tab1_line3.setGeometry(QtCore.QRect(70, 245, 248, 1))
        self.tab1_line3.setText("")
        self.tab1_line3.setPixmap(QtGui.QPixmap("pic/Line 3-2.png"))
        self.tab1_line3.setObjectName("tab1_line3")
        self.txt_xiakedu2_2.raise_()
        self.listWidget_1.raise_()
        self.label_2.raise_()
        self.label_8.raise_()
        self.label_1.raise_()
        self.alt_label1.raise_()
        self.alt_label2.raise_()
        self.alt_label3.raise_()
        self.label_7.raise_()
        self.label.raise_()
        self.label_lanse.raise_()
        self.angle_kedu_txt.raise_()
        self.tab1_own_pix.raise_()
        self.tab1_target1_info.raise_()
        self.tab1_target2_info.raise_()
        self.tab1_target3_info.raise_()
        self.tab1_target4_info.raise_()
        self.tab1_target5_info.raise_()
        self.tab1_target1_pix.raise_()
        self.tab1_target2_pix.raise_()
        self.tab1_target3_pix.raise_()
        self.tab1_target4_pix.raise_()
        self.tab1_target5_pix.raise_()
        self.tab1_line1.raise_()
        self.tab1_line2.raise_()
        self.tab1_line3.raise_()
        self.frame_1 = QtWidgets.QFrame(self.tab)
        self.frame_1.setGeometry(QtCore.QRect(5, 75, 580, 362))
        self.frame_1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_1.setLineWidth(2)
        self.frame_1.setObjectName("frame_1")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_1)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1026, 770))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(591, 75, 426, 362))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.txt_zuokedu2 = QtWidgets.QLabel(self.frame_2)
        self.txt_zuokedu2.setGeometry(QtCore.QRect(0, 30, 21, 301))
        self.txt_zuokedu2.setStyleSheet("color:white")
        self.txt_zuokedu2.setText("")
        self.txt_zuokedu2.setPixmap(QtGui.QPixmap("pic/zuokedu2(1).png"))
        self.txt_zuokedu2.setScaledContents(True)
        self.txt_zuokedu2.setObjectName("txt_zuokedu2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 161, 20))
        self.label_3.setStyleSheet("color:green")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(250, 10, 161, 20))
        self.label_4.setStyleSheet("color:green")
        self.label_4.setObjectName("label_4")
        self.txt_angle = QtWidgets.QLabel(self.frame_2)
        self.txt_angle.setGeometry(QtCore.QRect(180, 10, 31, 20))
        self.txt_angle.setStyleSheet("color:green")
        self.txt_angle.setObjectName("txt_angle")
        self.txt_xiakedu2_3 = QtWidgets.QLabel(self.frame_2)
        self.txt_xiakedu2_3.setGeometry(QtCore.QRect(34, 337, 314, 24))
        self.txt_xiakedu2_3.setStyleSheet("color:white")
        self.txt_xiakedu2_3.setText("")
        self.txt_xiakedu2_3.setPixmap(QtGui.QPixmap("pic/下刻度.png"))
        self.txt_xiakedu2_3.setScaledContents(False)
        self.txt_xiakedu2_3.setObjectName("txt_xiakedu2_3")
        self.listWidget_2 = QtWidgets.QListWidget(self.frame_2)
        self.listWidget_2.setGeometry(QtCore.QRect(355, 50, 45, 285))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label_lanse_2 = QtWidgets.QLabel(self.frame_2)
        self.label_lanse_2.setGeometry(QtCore.QRect(370, 170, 30, 46))
        self.label_lanse_2.setStyleSheet("background-color:transparent")
        self.label_lanse_2.setText("")
        self.label_lanse_2.setPixmap(QtGui.QPixmap("pic/fubiaolan.png"))
        self.label_lanse_2.setObjectName("label_lanse_2")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(380, 185, 21, 16))
        self.label_6.setStyleSheet("color:white;background-color:transparent")
        self.label_6.setObjectName("label_6")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(60, 70, 271, 241))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_zuokedu2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.txt_angle.raise_()
        self.listWidget_2.raise_()
        self.label_lanse_2.raise_()
        self.label_6.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.txt_xiakedu2_3.raise_()
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setGeometry(QtCore.QRect(5, 442, 580, 331))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName("frame_4")
        self.tabelWidget_1 = QtWidgets.QTableWidget(self.frame_4)
        self.tabelWidget_1.setGeometry(QtCore.QRect(10, 20, 561, 281))
        self.tabelWidget_1.setObjectName("tabelWidget_1")
        self.tabelWidget_1.setColumnCount(7)
        self.tabelWidget_1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tabelWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tabelWidget_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelWidget_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelWidget_1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelWidget_1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelWidget_1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelWidget_1.setHorizontalHeaderItem(6, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_5 = QtWidgets.QFrame(self.tab_2)
        self.frame_5.setGeometry(QtCore.QRect(603, 425, 411, 336))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(2)
        self.frame_5.setObjectName("frame_5")
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(20, 260, 18, 23))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("pic/gaodu2.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 18, 23))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("pic/gaodu2.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        self.label_14.setGeometry(QtCore.QRect(20, 140, 18, 23))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("pic/gaodu1.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.frame_5)
        self.label_16.setGeometry(QtCore.QRect(20, 80, 18, 23))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("pic/gaodu2.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_5)
        self.label_17.setGeometry(QtCore.QRect(20, 200, 18, 23))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("pic/gaodu2.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.txt_xiakedu2_4 = QtWidgets.QLabel(self.frame_5)
        self.txt_xiakedu2_4.setGeometry(QtCore.QRect(70, 290, 300, 10))
        self.txt_xiakedu2_4.setStyleSheet("color:white")
        self.txt_xiakedu2_4.setText("")
        self.txt_xiakedu2_4.setPixmap(QtGui.QPixmap("pic/kedu1.png"))
        self.txt_xiakedu2_4.setScaledContents(True)
        self.txt_xiakedu2_4.setObjectName("txt_xiakedu2_4")
        self.alt_label1_2 = QtWidgets.QLabel(self.frame_5)
        self.alt_label1_2.setGeometry(QtCore.QRect(40, 23, 31, 16))
        self.alt_label1_2.setStyleSheet("color:blue")
        self.alt_label1_2.setObjectName("alt_label1_2")
        self.alt_label2_2 = QtWidgets.QLabel(self.frame_5)
        self.alt_label2_2.setGeometry(QtCore.QRect(40, 84, 31, 16))
        self.alt_label2_2.setStyleSheet("color:blue")
        self.alt_label2_2.setObjectName("alt_label2_2")
        self.alt_label3_2 = QtWidgets.QLabel(self.frame_5)
        self.alt_label3_2.setGeometry(QtCore.QRect(40, 145, 31, 16))
        self.alt_label3_2.setStyleSheet("color:white")
        self.alt_label3_2.setObjectName("alt_label3_2")
        self.alt_label4 = QtWidgets.QLabel(self.frame_5)
        self.alt_label4.setGeometry(QtCore.QRect(40, 205, 31, 16))
        self.alt_label4.setStyleSheet("color:blue")
        self.alt_label4.setObjectName("alt_label4")
        self.alt_label5 = QtWidgets.QLabel(self.frame_5)
        self.alt_label5.setGeometry(QtCore.QRect(40, 265, 31, 16))
        self.alt_label5.setStyleSheet("color:blue")
        self.alt_label5.setObjectName("alt_label5")
        self.label_step4_1 = QtWidgets.QLabel(self.frame_5)
        self.label_step4_1.setGeometry(QtCore.QRect(60, 300, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_step4_1.setFont(font)
        self.label_step4_1.setStyleSheet("color:white")
        self.label_step4_1.setObjectName("label_step4_1")
        self.label_step4_7 = QtWidgets.QLabel(self.frame_5)
        self.label_step4_7.setGeometry(QtCore.QRect(140, 300, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_step4_7.setFont(font)
        self.label_step4_7.setStyleSheet("color:white")
        self.label_step4_7.setObjectName("label_step4_7")
        self.label_step4_9 = QtWidgets.QLabel(self.frame_5)
        self.label_step4_9.setGeometry(QtCore.QRect(215, 300, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_step4_9.setFont(font)
        self.label_step4_9.setStyleSheet("color:white")
        self.label_step4_9.setObjectName("label_step4_9")
        self.label_step4_8 = QtWidgets.QLabel(self.frame_5)
        self.label_step4_8.setGeometry(QtCore.QRect(285, 300, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_step4_8.setFont(font)
        self.label_step4_8.setStyleSheet("color:white")
        self.label_step4_8.setObjectName("label_step4_8")
        self.label_step4_10 = QtWidgets.QLabel(self.frame_5)
        self.label_step4_10.setGeometry(QtCore.QRect(355, 300, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_step4_10.setFont(font)
        self.label_step4_10.setStyleSheet("color:white")
        self.label_step4_10.setObjectName("label_step4_10")
        self.tab2_own_pix = QtWidgets.QLabel(self.frame_5)
        self.tab2_own_pix.setGeometry(QtCore.QRect(190, 150, 25, 10))
        self.tab2_own_pix.setText("")
        self.tab2_own_pix.setPixmap(QtGui.QPixmap("pic/benji.png"))
        self.tab2_own_pix.setObjectName("tab2_own_pix")
        self.tab2_line1 = QtWidgets.QLabel(self.frame_5)
        self.tab2_line1.setGeometry(QtCore.QRect(75, 30, 300, 1))
        self.tab2_line1.setText("")
        self.tab2_line1.setPixmap(QtGui.QPixmap("pic/Line 5-2.png"))
        self.tab2_line1.setObjectName("tab2_line1")
        self.tab2_line2 = QtWidgets.QLabel(self.frame_5)
        self.tab2_line2.setGeometry(QtCore.QRect(75, 90, 300, 1))
        self.tab2_line2.setText("")
        self.tab2_line2.setPixmap(QtGui.QPixmap("pic/Line 5-2.png"))
        self.tab2_line2.setObjectName("tab2_line2")
        self.tab2_line4 = QtWidgets.QLabel(self.frame_5)
        self.tab2_line4.setGeometry(QtCore.QRect(75, 215, 300, 1))
        self.tab2_line4.setText("")
        self.tab2_line4.setPixmap(QtGui.QPixmap("pic/Line 5-2.png"))
        self.tab2_line4.setObjectName("tab2_line4")
        self.tab2_line5 = QtWidgets.QLabel(self.frame_5)
        self.tab2_line5.setGeometry(QtCore.QRect(75, 275, 300, 1))
        self.tab2_line5.setText("")
        self.tab2_line5.setPixmap(QtGui.QPixmap("pic/Line 5-2.png"))
        self.tab2_line5.setObjectName("tab2_line5")
        self.tab2_line3 = QtWidgets.QLabel(self.frame_5)
        self.tab2_line3.setGeometry(QtCore.QRect(75, 150, 300, 1))
        self.tab2_line3.setText("")
        self.tab2_line3.setPixmap(QtGui.QPixmap("pic/Line 5-1.png"))
        self.tab2_line3.setObjectName("tab2_line3")
        self.tab2_target1_info = QtWidgets.QLabel(self.frame_5)
        self.tab2_target1_info.setGeometry(QtCore.QRect(140, 50, 51, 16))
        self.tab2_target1_info.setObjectName("tab2_target1_info")
        self.tab2_target2_info = QtWidgets.QLabel(self.frame_5)
        self.tab2_target2_info.setGeometry(QtCore.QRect(190, 50, 51, 16))
        self.tab2_target2_info.setObjectName("tab2_target2_info")
        self.tab2_target2_pix = QtWidgets.QLabel(self.frame_5)
        self.tab2_target2_pix.setGeometry(QtCore.QRect(260, 40, 25, 10))
        self.tab2_target2_pix.setText("")
        self.tab2_target2_pix.setPixmap(QtGui.QPixmap("pic/qtfeiji2.png"))
        self.tab2_target2_pix.setObjectName("tab2_target2_pix")
        self.tab2_target1_pix = QtWidgets.QLabel(self.frame_5)
        self.tab2_target1_pix.setGeometry(QtCore.QRect(100, 50, 25, 10))
        self.tab2_target1_pix.setText("")
        self.tab2_target1_pix.setPixmap(QtGui.QPixmap("pic/qtfeiji1.png"))
        self.tab2_target1_pix.setObjectName("tab2_target1_pix")
        self.tab2_target3_info = QtWidgets.QLabel(self.frame_5)
        self.tab2_target3_info.setGeometry(QtCore.QRect(310, 60, 51, 16))
        self.tab2_target3_info.setObjectName("tab2_target3_info")
        self.tab2_target3_pix = QtWidgets.QLabel(self.frame_5)
        self.tab2_target3_pix.setGeometry(QtCore.QRect(320, 40, 25, 10))
        self.tab2_target3_pix.setText("")
        self.tab2_target3_pix.setPixmap(QtGui.QPixmap("pic/qtfeiji3.png"))
        self.tab2_target3_pix.setObjectName("tab2_target3_pix")
        self.tab2_target5_pix = QtWidgets.QLabel(self.frame_5)
        self.tab2_target5_pix.setGeometry(QtCore.QRect(260, 70, 25, 10))
        self.tab2_target5_pix.setText("")
        self.tab2_target5_pix.setPixmap(QtGui.QPixmap("pic/benji.png"))
        self.tab2_target5_pix.setObjectName("tab2_target5_pix")
        self.tab2_target5_info = QtWidgets.QLabel(self.frame_5)
        self.tab2_target5_info.setGeometry(QtCore.QRect(260, 80, 51, 16))
        self.tab2_target5_info.setObjectName("tab2_target5_info")
        self.tab2_target4_pix = QtWidgets.QLabel(self.frame_5)
        self.tab2_target4_pix.setGeometry(QtCore.QRect(60, 60, 25, 16))
        self.tab2_target4_pix.setText("")
        self.tab2_target4_pix.setPixmap(QtGui.QPixmap("pic/benji.png"))
        self.tab2_target4_pix.setObjectName("tab2_target4_pix")
        self.tab2_target4_info = QtWidgets.QLabel(self.frame_5)
        self.tab2_target4_info.setGeometry(QtCore.QRect(60, 40, 51, 16))
        self.tab2_target4_info.setObjectName("tab2_target4_info")
        self.frame_6 = QtWidgets.QFrame(self.tab_2)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 598, 764))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setLineWidth(2)
        self.frame_6.setObjectName("frame_6")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(34, 26, 32, 32))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("pic/shezhi.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setGeometry(QtCore.QRect(144, 24, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:blue")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        self.label_11.setGeometry(QtCore.QRect(200, 710, 261, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:white")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        self.label_12.setGeometry(QtCore.QRect(470, 680, 111, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:white")
        self.label_12.setObjectName("label_12")
        self.label_18 = QtWidgets.QLabel(self.frame_6)
        self.label_18.setGeometry(QtCore.QRect(22, 710, 24, 24))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("pic/放大.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(54, 710, 24, 24))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("pic/缩小.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame_6)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(80, 130, 481, 481))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.angle_txt = QtWidgets.QLabel(self.frame_6)
        self.angle_txt.setGeometry(QtCore.QRect(320, 70, 41, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.angle_txt.setFont(font)
        self.angle_txt.setStyleSheet("color:blue")
        self.angle_txt.setObjectName("angle_txt")
        self.label_step1 = QtWidgets.QLabel(self.frame_6)
        self.label_step1.setGeometry(QtCore.QRect(20, 124, 40, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_step1.setFont(font)
        self.label_step1.setStyleSheet("color:white")
        self.label_step1.setObjectName("label_step1")
        self.label_step2 = QtWidgets.QLabel(self.frame_6)
        self.label_step2.setGeometry(QtCore.QRect(20, 247, 40, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_step2.setFont(font)
        self.label_step2.setStyleSheet("color:white")
        self.label_step2.setObjectName("label_step2")
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        self.label_20.setGeometry(QtCore.QRect(20, 370, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:white")
        self.label_20.setObjectName("label_20")
        self.label_step3 = QtWidgets.QLabel(self.frame_6)
        self.label_step3.setGeometry(QtCore.QRect(20, 486, 40, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_step3.setFont(font)
        self.label_step3.setStyleSheet("color:white")
        self.label_step3.setObjectName("label_step3")
        self.label_step4 = QtWidgets.QLabel(self.frame_6)
        self.label_step4.setGeometry(QtCore.QRect(20, 601, 40, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_step4.setFont(font)
        self.label_step4.setStyleSheet("color:white")
        self.label_step4.setObjectName("label_step4")
        self.label_step4_2 = QtWidgets.QLabel(self.frame_6)
        self.label_step4_2.setGeometry(QtCore.QRect(70, 651, 40, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_step4_2.setFont(font)
        self.label_step4_2.setStyleSheet("color:white")
        self.label_step4_2.setObjectName("label_step4_2")
        self.label_step4_3 = QtWidgets.QLabel(self.frame_6)
        self.label_step4_3.setGeometry(QtCore.QRect(200, 651, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_step4_3.setFont(font)
        self.label_step4_3.setStyleSheet("color:white")
        self.label_step4_3.setObjectName("label_step4_3")
        self.label_step4_4 = QtWidgets.QLabel(self.frame_6)
        self.label_step4_4.setGeometry(QtCore.QRect(320, 651, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_step4_4.setFont(font)
        self.label_step4_4.setStyleSheet("color:white")
        self.label_step4_4.setObjectName("label_step4_4")
        self.label_step4_5 = QtWidgets.QLabel(self.frame_6)
        self.label_step4_5.setGeometry(QtCore.QRect(430, 651, 40, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_step4_5.setFont(font)
        self.label_step4_5.setStyleSheet("color:white")
        self.label_step4_5.setObjectName("label_step4_5")
        self.label_step4_6 = QtWidgets.QLabel(self.frame_6)
        self.label_step4_6.setGeometry(QtCore.QRect(550, 651, 40, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_step4_6.setFont(font)
        self.label_step4_6.setStyleSheet("color:white")
        self.label_step4_6.setObjectName("label_step4_6")
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        self.label_21.setGeometry(QtCore.QRect(60, 130, 10, 480))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("pic/kedu.png"))
        self.label_21.setScaledContents(False)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_6)
        self.label_22.setGeometry(QtCore.QRect(80, 630, 481, 10))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("pic/kedu1.png"))
        self.label_22.setObjectName("label_22")
        self.btn_jump2 = QtWidgets.QPushButton(self.frame_6)
        self.btn_jump2.setGeometry(QtCore.QRect(504, 2, 91, 61))
        self.btn_jump2.setStyleSheet("color:white")
        self.btn_jump2.setObjectName("btn_jump2")
        self.frame_7 = QtWidgets.QFrame(self.tab_2)
        self.frame_7.setGeometry(QtCore.QRect(603, 0, 411, 421))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setLineWidth(2)
        self.frame_7.setObjectName("frame_7")
        self.btn2 = QtWidgets.QPushButton(self.frame_7)
        self.btn2.setGeometry(QtCore.QRect(140, 10, 136, 64))
        self.btn2.setStyleSheet("color:white")
        self.btn2.setText("")
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.frame_7)
        self.btn3.setGeometry(QtCore.QRect(270, 10, 136, 64))
        self.btn3.setStyleSheet("color:white")
        self.btn3.setText("")
        self.btn3.setObjectName("btn3")
        self.btn1 = QtWidgets.QPushButton(self.frame_7)
        self.btn1.setGeometry(QtCore.QRect(5, 10, 136, 64))
        self.btn1.setStyleSheet("color:red")
        self.btn1.setText("")
        self.btn1.setObjectName("btn1")
        self.label_23 = QtWidgets.QLabel(self.frame_7)
        self.label_23.setGeometry(QtCore.QRect(80, 30, 30, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color:red;background-color:transparent")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_7)
        self.label_24.setGeometry(QtCore.QRect(190, 30, 30, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color:white;background-color:transparent")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_7)
        self.label_25.setGeometry(QtCore.QRect(300, 30, 136, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color:white;background-color:transparent")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_7)
        self.label_26.setGeometry(QtCore.QRect(30, 30, 31, 20))
        self.label_26.setStyleSheet("background-color:transparent")
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("pic/weixian.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_7)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 240, 391, 171))
        self.textBrowser_3.setStyleSheet("color:#40E0D0")
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_7)
        self.textBrowser.setGeometry(QtCore.QRect(10, 100, 191, 111))
        self.textBrowser.setStyleSheet("color:#40E0D0")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_7)
        self.textBrowser_2.setGeometry(QtCore.QRect(210, 100, 191, 111))
        self.textBrowser_2.setStyleSheet("color:#40E0D0")
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_27 = QtWidgets.QLabel(self.frame_7)
        self.label_27.setGeometry(QtCore.QRect(10, 80, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color:white")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_7)
        self.label_28.setGeometry(QtCore.QRect(10, 220, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color:white")
        self.label_28.setObjectName("label_28")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Horizontal Maneuver"))
        self.btn_jump1.setText(_translate("MainWindow", "Jump"))
        self.alt_label1.setText(_translate("MainWindow", "111"))
        self.alt_label2.setText(_translate("MainWindow", "111"))
        self.alt_label3.setText(_translate("MainWindow", "111"))
        self.angle_kedu_txt.setText(_translate("MainWindow", "39000"))
        self.tab1_target1_info.setText(_translate("MainWindow", "target1"))
        self.tab1_target2_info.setText(_translate("MainWindow", "target2"))
        self.tab1_target3_info.setText(_translate("MainWindow", "target3"))
        self.tab1_target4_info.setText(_translate("MainWindow", "target4"))
        self.tab1_target5_info.setText(_translate("MainWindow", "target5"))
        self.label_3.setText(_translate("MainWindow", "Horizontal Maneuver"))
        self.label_4.setText(_translate("MainWindow", "Horizontal Maneuver"))
        self.txt_angle.setText(_translate("MainWindow", "126"))
        self.label_6.setText(_translate("MainWindow", "486"))
        item = self.tabelWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "飞机ID号"))
        item = self.tabelWidget_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "高度"))
        item = self.tabelWidget_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "经度"))
        item = self.tabelWidget_1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "维度"))
        item = self.tabelWidget_1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "地速"))
        item = self.tabelWidget_1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "垂直速度"))
        item = self.tabelWidget_1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "航向角"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.alt_label1_2.setText(_translate("MainWindow", "111"))
        self.alt_label2_2.setText(_translate("MainWindow", "222"))
        self.alt_label3_2.setText(_translate("MainWindow", "333"))
        self.alt_label4.setText(_translate("MainWindow", "444"))
        self.alt_label5.setText(_translate("MainWindow", "555"))
        self.label_step4_1.setText(_translate("MainWindow", "16"))
        self.label_step4_7.setText(_translate("MainWindow", "8"))
        self.label_step4_9.setText(_translate("MainWindow", "0"))
        self.label_step4_8.setText(_translate("MainWindow", "-8"))
        self.label_step4_10.setText(_translate("MainWindow", "-16"))
        self.tab2_target1_info.setText(_translate("MainWindow", "target1"))
        self.tab2_target2_info.setText(_translate("MainWindow", "target2"))
        self.tab2_target3_info.setText(_translate("MainWindow", "target3"))
        self.tab2_target5_info.setText(_translate("MainWindow", "target5"))
        self.tab2_target4_info.setText(_translate("MainWindow", "target4"))
        self.label_10.setText(_translate("MainWindow", "工作说明文字"))
        self.label_11.setText(_translate("MainWindow", "N N/A E N/A"))
        self.label_12.setText(_translate("MainWindow", "DES"))
        self.angle_txt.setText(_translate("MainWindow", "6"))
        self.label_step1.setText(_translate("MainWindow", "1600"))
        self.label_step2.setText(_translate("MainWindow", "800"))
        self.label_20.setText(_translate("MainWindow", "0"))
        self.label_step3.setText(_translate("MainWindow", "-800"))
        self.label_step4.setText(_translate("MainWindow", "-1600"))
        self.label_step4_2.setText(_translate("MainWindow", "1600"))
        self.label_step4_3.setText(_translate("MainWindow", "800"))
        self.label_step4_4.setText(_translate("MainWindow", "0"))
        self.label_step4_5.setText(_translate("MainWindow", "-800"))
        self.label_step4_6.setText(_translate("MainWindow", "-1600"))
        self.btn_jump2.setText(_translate("MainWindow", "Jump"))
        self.label_23.setText(_translate("MainWindow", "RA"))
        self.label_24.setText(_translate("MainWindow", "TA"))
        self.label_25.setText(_translate("MainWindow", "CLC"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "Location"))
        self.label_28.setText(_translate("MainWindow", "Speed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

